// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: interactions/v1/interactions.proto

package interactionsv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InteractionsService_LikePost_FullMethodName          = "/interactions.v1.InteractionsService/LikePost"
	InteractionsService_UnlikePost_FullMethodName        = "/interactions.v1.InteractionsService/UnlikePost"
	InteractionsService_GetPostLikes_FullMethodName      = "/interactions.v1.InteractionsService/GetPostLikes"
	InteractionsService_AddReaction_FullMethodName       = "/interactions.v1.InteractionsService/AddReaction"
	InteractionsService_RemoveReaction_FullMethodName    = "/interactions.v1.InteractionsService/RemoveReaction"
	InteractionsService_GetPostReactions_FullMethodName  = "/interactions.v1.InteractionsService/GetPostReactions"
	InteractionsService_CreateComment_FullMethodName     = "/interactions.v1.InteractionsService/CreateComment"
	InteractionsService_GetComment_FullMethodName        = "/interactions.v1.InteractionsService/GetComment"
	InteractionsService_UpdateComment_FullMethodName     = "/interactions.v1.InteractionsService/UpdateComment"
	InteractionsService_DeleteComment_FullMethodName     = "/interactions.v1.InteractionsService/DeleteComment"
	InteractionsService_GetPostComments_FullMethodName   = "/interactions.v1.InteractionsService/GetPostComments"
	InteractionsService_GetCommentReplies_FullMethodName = "/interactions.v1.InteractionsService/GetCommentReplies"
	InteractionsService_LikeComment_FullMethodName       = "/interactions.v1.InteractionsService/LikeComment"
	InteractionsService_UnlikeComment_FullMethodName     = "/interactions.v1.InteractionsService/UnlikeComment"
	InteractionsService_BookmarkPost_FullMethodName      = "/interactions.v1.InteractionsService/BookmarkPost"
	InteractionsService_UnbookmarkPost_FullMethodName    = "/interactions.v1.InteractionsService/UnbookmarkPost"
	InteractionsService_GetBookmarks_FullMethodName      = "/interactions.v1.InteractionsService/GetBookmarks"
	InteractionsService_SharePost_FullMethodName         = "/interactions.v1.InteractionsService/SharePost"
	InteractionsService_GetPostShares_FullMethodName     = "/interactions.v1.InteractionsService/GetPostShares"
	InteractionsService_ReportContent_FullMethodName     = "/interactions.v1.InteractionsService/ReportContent"
	InteractionsService_StreamComments_FullMethodName    = "/interactions.v1.InteractionsService/StreamComments"
)

// InteractionsServiceClient is the client API for InteractionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Interactions service handles likes, comments, reactions, and bookmarks
type InteractionsServiceClient interface {
	// Like a post
	LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error)
	// Unlike a post
	UnlikePost(ctx context.Context, in *UnlikePostRequest, opts ...grpc.CallOption) (*UnlikePostResponse, error)
	// Get users who liked a post
	GetPostLikes(ctx context.Context, in *GetPostLikesRequest, opts ...grpc.CallOption) (*GetPostLikesResponse, error)
	// Add a reaction to a post
	AddReaction(ctx context.Context, in *AddReactionRequest, opts ...grpc.CallOption) (*AddReactionResponse, error)
	// Remove a reaction from a post
	RemoveReaction(ctx context.Context, in *RemoveReactionRequest, opts ...grpc.CallOption) (*RemoveReactionResponse, error)
	// Get reactions for a post
	GetPostReactions(ctx context.Context, in *GetPostReactionsRequest, opts ...grpc.CallOption) (*GetPostReactionsResponse, error)
	// Create a comment on a post
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	// Get comment by ID
	GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error)
	// Update a comment
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
	// Delete a comment
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	// Get comments for a post
	GetPostComments(ctx context.Context, in *GetPostCommentsRequest, opts ...grpc.CallOption) (*GetPostCommentsResponse, error)
	// Get replies to a comment
	GetCommentReplies(ctx context.Context, in *GetCommentRepliesRequest, opts ...grpc.CallOption) (*GetCommentRepliesResponse, error)
	// Like a comment
	LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error)
	// Unlike a comment
	UnlikeComment(ctx context.Context, in *UnlikeCommentRequest, opts ...grpc.CallOption) (*UnlikeCommentResponse, error)
	// Bookmark a post
	BookmarkPost(ctx context.Context, in *BookmarkPostRequest, opts ...grpc.CallOption) (*BookmarkPostResponse, error)
	// Remove bookmark from a post
	UnbookmarkPost(ctx context.Context, in *UnbookmarkPostRequest, opts ...grpc.CallOption) (*UnbookmarkPostResponse, error)
	// Get user's bookmarked posts
	GetBookmarks(ctx context.Context, in *GetBookmarksRequest, opts ...grpc.CallOption) (*GetBookmarksResponse, error)
	// Share/repost a post
	SharePost(ctx context.Context, in *SharePostRequest, opts ...grpc.CallOption) (*SharePostResponse, error)
	// Get shares of a post
	GetPostShares(ctx context.Context, in *GetPostSharesRequest, opts ...grpc.CallOption) (*GetPostSharesResponse, error)
	// Report content (post or comment)
	ReportContent(ctx context.Context, in *ReportContentRequest, opts ...grpc.CallOption) (*ReportContentResponse, error)
	// Stream real-time comments (server streaming)
	StreamComments(ctx context.Context, in *StreamCommentsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommentEvent], error)
}

type interactionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionsServiceClient(cc grpc.ClientConnInterface) InteractionsServiceClient {
	return &interactionsServiceClient{cc}
}

func (c *interactionsServiceClient) LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikePostResponse)
	err := c.cc.Invoke(ctx, InteractionsService_LikePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) UnlikePost(ctx context.Context, in *UnlikePostRequest, opts ...grpc.CallOption) (*UnlikePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikePostResponse)
	err := c.cc.Invoke(ctx, InteractionsService_UnlikePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) GetPostLikes(ctx context.Context, in *GetPostLikesRequest, opts ...grpc.CallOption) (*GetPostLikesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostLikesResponse)
	err := c.cc.Invoke(ctx, InteractionsService_GetPostLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) AddReaction(ctx context.Context, in *AddReactionRequest, opts ...grpc.CallOption) (*AddReactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddReactionResponse)
	err := c.cc.Invoke(ctx, InteractionsService_AddReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) RemoveReaction(ctx context.Context, in *RemoveReactionRequest, opts ...grpc.CallOption) (*RemoveReactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveReactionResponse)
	err := c.cc.Invoke(ctx, InteractionsService_RemoveReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) GetPostReactions(ctx context.Context, in *GetPostReactionsRequest, opts ...grpc.CallOption) (*GetPostReactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostReactionsResponse)
	err := c.cc.Invoke(ctx, InteractionsService_GetPostReactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, InteractionsService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentResponse)
	err := c.cc.Invoke(ctx, InteractionsService_GetComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCommentResponse)
	err := c.cc.Invoke(ctx, InteractionsService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, InteractionsService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) GetPostComments(ctx context.Context, in *GetPostCommentsRequest, opts ...grpc.CallOption) (*GetPostCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostCommentsResponse)
	err := c.cc.Invoke(ctx, InteractionsService_GetPostComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) GetCommentReplies(ctx context.Context, in *GetCommentRepliesRequest, opts ...grpc.CallOption) (*GetCommentRepliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentRepliesResponse)
	err := c.cc.Invoke(ctx, InteractionsService_GetCommentReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeCommentResponse)
	err := c.cc.Invoke(ctx, InteractionsService_LikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) UnlikeComment(ctx context.Context, in *UnlikeCommentRequest, opts ...grpc.CallOption) (*UnlikeCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeCommentResponse)
	err := c.cc.Invoke(ctx, InteractionsService_UnlikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) BookmarkPost(ctx context.Context, in *BookmarkPostRequest, opts ...grpc.CallOption) (*BookmarkPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookmarkPostResponse)
	err := c.cc.Invoke(ctx, InteractionsService_BookmarkPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) UnbookmarkPost(ctx context.Context, in *UnbookmarkPostRequest, opts ...grpc.CallOption) (*UnbookmarkPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbookmarkPostResponse)
	err := c.cc.Invoke(ctx, InteractionsService_UnbookmarkPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) GetBookmarks(ctx context.Context, in *GetBookmarksRequest, opts ...grpc.CallOption) (*GetBookmarksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookmarksResponse)
	err := c.cc.Invoke(ctx, InteractionsService_GetBookmarks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) SharePost(ctx context.Context, in *SharePostRequest, opts ...grpc.CallOption) (*SharePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SharePostResponse)
	err := c.cc.Invoke(ctx, InteractionsService_SharePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) GetPostShares(ctx context.Context, in *GetPostSharesRequest, opts ...grpc.CallOption) (*GetPostSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostSharesResponse)
	err := c.cc.Invoke(ctx, InteractionsService_GetPostShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) ReportContent(ctx context.Context, in *ReportContentRequest, opts ...grpc.CallOption) (*ReportContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportContentResponse)
	err := c.cc.Invoke(ctx, InteractionsService_ReportContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) StreamComments(ctx context.Context, in *StreamCommentsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InteractionsService_ServiceDesc.Streams[0], InteractionsService_StreamComments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCommentsRequest, CommentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InteractionsService_StreamCommentsClient = grpc.ServerStreamingClient[CommentEvent]

// InteractionsServiceServer is the server API for InteractionsService service.
// All implementations must embed UnimplementedInteractionsServiceServer
// for forward compatibility.
//
// Interactions service handles likes, comments, reactions, and bookmarks
type InteractionsServiceServer interface {
	// Like a post
	LikePost(context.Context, *LikePostRequest) (*LikePostResponse, error)
	// Unlike a post
	UnlikePost(context.Context, *UnlikePostRequest) (*UnlikePostResponse, error)
	// Get users who liked a post
	GetPostLikes(context.Context, *GetPostLikesRequest) (*GetPostLikesResponse, error)
	// Add a reaction to a post
	AddReaction(context.Context, *AddReactionRequest) (*AddReactionResponse, error)
	// Remove a reaction from a post
	RemoveReaction(context.Context, *RemoveReactionRequest) (*RemoveReactionResponse, error)
	// Get reactions for a post
	GetPostReactions(context.Context, *GetPostReactionsRequest) (*GetPostReactionsResponse, error)
	// Create a comment on a post
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	// Get comment by ID
	GetComment(context.Context, *GetCommentRequest) (*GetCommentResponse, error)
	// Update a comment
	UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error)
	// Delete a comment
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	// Get comments for a post
	GetPostComments(context.Context, *GetPostCommentsRequest) (*GetPostCommentsResponse, error)
	// Get replies to a comment
	GetCommentReplies(context.Context, *GetCommentRepliesRequest) (*GetCommentRepliesResponse, error)
	// Like a comment
	LikeComment(context.Context, *LikeCommentRequest) (*LikeCommentResponse, error)
	// Unlike a comment
	UnlikeComment(context.Context, *UnlikeCommentRequest) (*UnlikeCommentResponse, error)
	// Bookmark a post
	BookmarkPost(context.Context, *BookmarkPostRequest) (*BookmarkPostResponse, error)
	// Remove bookmark from a post
	UnbookmarkPost(context.Context, *UnbookmarkPostRequest) (*UnbookmarkPostResponse, error)
	// Get user's bookmarked posts
	GetBookmarks(context.Context, *GetBookmarksRequest) (*GetBookmarksResponse, error)
	// Share/repost a post
	SharePost(context.Context, *SharePostRequest) (*SharePostResponse, error)
	// Get shares of a post
	GetPostShares(context.Context, *GetPostSharesRequest) (*GetPostSharesResponse, error)
	// Report content (post or comment)
	ReportContent(context.Context, *ReportContentRequest) (*ReportContentResponse, error)
	// Stream real-time comments (server streaming)
	StreamComments(*StreamCommentsRequest, grpc.ServerStreamingServer[CommentEvent]) error
	mustEmbedUnimplementedInteractionsServiceServer()
}

// UnimplementedInteractionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionsServiceServer struct{}

func (UnimplementedInteractionsServiceServer) LikePost(context.Context, *LikePostRequest) (*LikePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikePost not implemented")
}
func (UnimplementedInteractionsServiceServer) UnlikePost(context.Context, *UnlikePostRequest) (*UnlikePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlikePost not implemented")
}
func (UnimplementedInteractionsServiceServer) GetPostLikes(context.Context, *GetPostLikesRequest) (*GetPostLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLikes not implemented")
}
func (UnimplementedInteractionsServiceServer) AddReaction(context.Context, *AddReactionRequest) (*AddReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReaction not implemented")
}
func (UnimplementedInteractionsServiceServer) RemoveReaction(context.Context, *RemoveReactionRequest) (*RemoveReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveReaction not implemented")
}
func (UnimplementedInteractionsServiceServer) GetPostReactions(context.Context, *GetPostReactionsRequest) (*GetPostReactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostReactions not implemented")
}
func (UnimplementedInteractionsServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedInteractionsServiceServer) GetComment(context.Context, *GetCommentRequest) (*GetCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}
func (UnimplementedInteractionsServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedInteractionsServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedInteractionsServiceServer) GetPostComments(context.Context, *GetPostCommentsRequest) (*GetPostCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostComments not implemented")
}
func (UnimplementedInteractionsServiceServer) GetCommentReplies(context.Context, *GetCommentRepliesRequest) (*GetCommentRepliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentReplies not implemented")
}
func (UnimplementedInteractionsServiceServer) LikeComment(context.Context, *LikeCommentRequest) (*LikeCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedInteractionsServiceServer) UnlikeComment(context.Context, *UnlikeCommentRequest) (*UnlikeCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlikeComment not implemented")
}
func (UnimplementedInteractionsServiceServer) BookmarkPost(context.Context, *BookmarkPostRequest) (*BookmarkPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookmarkPost not implemented")
}
func (UnimplementedInteractionsServiceServer) UnbookmarkPost(context.Context, *UnbookmarkPostRequest) (*UnbookmarkPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbookmarkPost not implemented")
}
func (UnimplementedInteractionsServiceServer) GetBookmarks(context.Context, *GetBookmarksRequest) (*GetBookmarksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookmarks not implemented")
}
func (UnimplementedInteractionsServiceServer) SharePost(context.Context, *SharePostRequest) (*SharePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SharePost not implemented")
}
func (UnimplementedInteractionsServiceServer) GetPostShares(context.Context, *GetPostSharesRequest) (*GetPostSharesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostShares not implemented")
}
func (UnimplementedInteractionsServiceServer) ReportContent(context.Context, *ReportContentRequest) (*ReportContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportContent not implemented")
}
func (UnimplementedInteractionsServiceServer) StreamComments(*StreamCommentsRequest, grpc.ServerStreamingServer[CommentEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamComments not implemented")
}
func (UnimplementedInteractionsServiceServer) mustEmbedUnimplementedInteractionsServiceServer() {}
func (UnimplementedInteractionsServiceServer) testEmbeddedByValue()                             {}

// UnsafeInteractionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionsServiceServer will
// result in compilation errors.
type UnsafeInteractionsServiceServer interface {
	mustEmbedUnimplementedInteractionsServiceServer()
}

func RegisterInteractionsServiceServer(s grpc.ServiceRegistrar, srv InteractionsServiceServer) {
	// If the following call pancis, it indicates UnimplementedInteractionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionsService_ServiceDesc, srv)
}

func _InteractionsService_LikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).LikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_LikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).LikePost(ctx, req.(*LikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_UnlikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).UnlikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_UnlikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).UnlikePost(ctx, req.(*UnlikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_GetPostLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).GetPostLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_GetPostLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).GetPostLikes(ctx, req.(*GetPostLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_AddReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).AddReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_AddReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).AddReaction(ctx, req.(*AddReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_RemoveReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).RemoveReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_RemoveReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).RemoveReaction(ctx, req.(*RemoveReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_GetPostReactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostReactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).GetPostReactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_GetPostReactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).GetPostReactions(ctx, req.(*GetPostReactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_GetComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).GetComment(ctx, req.(*GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_GetPostComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).GetPostComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_GetPostComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).GetPostComments(ctx, req.(*GetPostCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_GetCommentReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).GetCommentReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_GetCommentReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).GetCommentReplies(ctx, req.(*GetCommentRepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_LikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).LikeComment(ctx, req.(*LikeCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_UnlikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).UnlikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_UnlikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).UnlikeComment(ctx, req.(*UnlikeCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_BookmarkPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookmarkPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).BookmarkPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_BookmarkPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).BookmarkPost(ctx, req.(*BookmarkPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_UnbookmarkPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbookmarkPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).UnbookmarkPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_UnbookmarkPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).UnbookmarkPost(ctx, req.(*UnbookmarkPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_GetBookmarks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookmarksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).GetBookmarks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_GetBookmarks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).GetBookmarks(ctx, req.(*GetBookmarksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_SharePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SharePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).SharePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_SharePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).SharePost(ctx, req.(*SharePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_GetPostShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).GetPostShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_GetPostShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).GetPostShares(ctx, req.(*GetPostSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_ReportContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).ReportContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionsService_ReportContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).ReportContent(ctx, req.(*ReportContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_StreamComments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCommentsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InteractionsServiceServer).StreamComments(m, &grpc.GenericServerStream[StreamCommentsRequest, CommentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InteractionsService_StreamCommentsServer = grpc.ServerStreamingServer[CommentEvent]

// InteractionsService_ServiceDesc is the grpc.ServiceDesc for InteractionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interactions.v1.InteractionsService",
	HandlerType: (*InteractionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikePost",
			Handler:    _InteractionsService_LikePost_Handler,
		},
		{
			MethodName: "UnlikePost",
			Handler:    _InteractionsService_UnlikePost_Handler,
		},
		{
			MethodName: "GetPostLikes",
			Handler:    _InteractionsService_GetPostLikes_Handler,
		},
		{
			MethodName: "AddReaction",
			Handler:    _InteractionsService_AddReaction_Handler,
		},
		{
			MethodName: "RemoveReaction",
			Handler:    _InteractionsService_RemoveReaction_Handler,
		},
		{
			MethodName: "GetPostReactions",
			Handler:    _InteractionsService_GetPostReactions_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _InteractionsService_CreateComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _InteractionsService_GetComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _InteractionsService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _InteractionsService_DeleteComment_Handler,
		},
		{
			MethodName: "GetPostComments",
			Handler:    _InteractionsService_GetPostComments_Handler,
		},
		{
			MethodName: "GetCommentReplies",
			Handler:    _InteractionsService_GetCommentReplies_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _InteractionsService_LikeComment_Handler,
		},
		{
			MethodName: "UnlikeComment",
			Handler:    _InteractionsService_UnlikeComment_Handler,
		},
		{
			MethodName: "BookmarkPost",
			Handler:    _InteractionsService_BookmarkPost_Handler,
		},
		{
			MethodName: "UnbookmarkPost",
			Handler:    _InteractionsService_UnbookmarkPost_Handler,
		},
		{
			MethodName: "GetBookmarks",
			Handler:    _InteractionsService_GetBookmarks_Handler,
		},
		{
			MethodName: "SharePost",
			Handler:    _InteractionsService_SharePost_Handler,
		},
		{
			MethodName: "GetPostShares",
			Handler:    _InteractionsService_GetPostShares_Handler,
		},
		{
			MethodName: "ReportContent",
			Handler:    _InteractionsService_ReportContent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamComments",
			Handler:       _InteractionsService_StreamComments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "interactions/v1/interactions.proto",
}
