// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: presence/v1/presence.proto

package presencev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "github.com/0xsj/nexus/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Online status
type OnlineStatus int32

const (
	OnlineStatus_ONLINE_STATUS_UNSPECIFIED OnlineStatus = 0
	OnlineStatus_ONLINE_STATUS_ONLINE      OnlineStatus = 1
	OnlineStatus_ONLINE_STATUS_AWAY        OnlineStatus = 2
	OnlineStatus_ONLINE_STATUS_BUSY        OnlineStatus = 3
	OnlineStatus_ONLINE_STATUS_OFFLINE     OnlineStatus = 4
	OnlineStatus_ONLINE_STATUS_INVISIBLE   OnlineStatus = 5 // Appear offline
)

// Enum value maps for OnlineStatus.
var (
	OnlineStatus_name = map[int32]string{
		0: "ONLINE_STATUS_UNSPECIFIED",
		1: "ONLINE_STATUS_ONLINE",
		2: "ONLINE_STATUS_AWAY",
		3: "ONLINE_STATUS_BUSY",
		4: "ONLINE_STATUS_OFFLINE",
		5: "ONLINE_STATUS_INVISIBLE",
	}
	OnlineStatus_value = map[string]int32{
		"ONLINE_STATUS_UNSPECIFIED": 0,
		"ONLINE_STATUS_ONLINE":      1,
		"ONLINE_STATUS_AWAY":        2,
		"ONLINE_STATUS_BUSY":        3,
		"ONLINE_STATUS_OFFLINE":     4,
		"ONLINE_STATUS_INVISIBLE":   5,
	}
)

func (x OnlineStatus) Enum() *OnlineStatus {
	p := new(OnlineStatus)
	*p = x
	return p
}

func (x OnlineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnlineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_presence_v1_presence_proto_enumTypes[0].Descriptor()
}

func (OnlineStatus) Type() protoreflect.EnumType {
	return &file_presence_v1_presence_proto_enumTypes[0]
}

func (x OnlineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnlineStatus.Descriptor instead.
func (OnlineStatus) EnumDescriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{0}
}

// Activity type
type ActivityType int32

const (
	ActivityType_ACTIVITY_TYPE_UNSPECIFIED ActivityType = 0
	ActivityType_ACTIVITY_TYPE_BROWSING    ActivityType = 1
	ActivityType_ACTIVITY_TYPE_TYPING      ActivityType = 2
	ActivityType_ACTIVITY_TYPE_RECORDING   ActivityType = 3 // Recording audio/video
	ActivityType_ACTIVITY_TYPE_IN_CALL     ActivityType = 4
	ActivityType_ACTIVITY_TYPE_PLAYING     ActivityType = 5 // Gaming
	ActivityType_ACTIVITY_TYPE_LISTENING   ActivityType = 6 // Music
	ActivityType_ACTIVITY_TYPE_WATCHING    ActivityType = 7 // Video
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0: "ACTIVITY_TYPE_UNSPECIFIED",
		1: "ACTIVITY_TYPE_BROWSING",
		2: "ACTIVITY_TYPE_TYPING",
		3: "ACTIVITY_TYPE_RECORDING",
		4: "ACTIVITY_TYPE_IN_CALL",
		5: "ACTIVITY_TYPE_PLAYING",
		6: "ACTIVITY_TYPE_LISTENING",
		7: "ACTIVITY_TYPE_WATCHING",
	}
	ActivityType_value = map[string]int32{
		"ACTIVITY_TYPE_UNSPECIFIED": 0,
		"ACTIVITY_TYPE_BROWSING":    1,
		"ACTIVITY_TYPE_TYPING":      2,
		"ACTIVITY_TYPE_RECORDING":   3,
		"ACTIVITY_TYPE_IN_CALL":     4,
		"ACTIVITY_TYPE_PLAYING":     5,
		"ACTIVITY_TYPE_LISTENING":   6,
		"ACTIVITY_TYPE_WATCHING":    7,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_presence_v1_presence_proto_enumTypes[1].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_presence_v1_presence_proto_enumTypes[1]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{1}
}

// Presence information
type Presence struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status     OnlineStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=presence.v1.OnlineStatus" json:"status,omitempty"`
	LastSeenAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	// Custom status
	CustomStatus *CustomStatus `protobuf:"bytes,4,opt,name=custom_status,json=customStatus,proto3,oneof" json:"custom_status,omitempty"`
	// Current activity
	Activity *Activity `protobuf:"bytes,5,opt,name=activity,proto3,oneof" json:"activity,omitempty"`
	// Device info
	Devices []*Device `protobuf:"bytes,6,rep,name=devices,proto3" json:"devices,omitempty"`
	// Available/idle time
	IdleSince *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=idle_since,json=idleSince,proto3,oneof" json:"idle_since,omitempty"`
	// Calculated status
	IsOnline      bool `protobuf:"varint,8,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	IsAway        bool `protobuf:"varint,9,opt,name=is_away,json=isAway,proto3" json:"is_away,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Presence) Reset() {
	*x = Presence{}
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Presence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presence) ProtoMessage() {}

func (x *Presence) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presence.ProtoReflect.Descriptor instead.
func (*Presence) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *Presence) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Presence) GetStatus() OnlineStatus {
	if x != nil {
		return x.Status
	}
	return OnlineStatus_ONLINE_STATUS_UNSPECIFIED
}

func (x *Presence) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *Presence) GetCustomStatus() *CustomStatus {
	if x != nil {
		return x.CustomStatus
	}
	return nil
}

func (x *Presence) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *Presence) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *Presence) GetIdleSince() *timestamppb.Timestamp {
	if x != nil {
		return x.IdleSince
	}
	return nil
}

func (x *Presence) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *Presence) GetIsAway() bool {
	if x != nil {
		return x.IsAway
	}
	return false
}

// Custom status message
type CustomStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Emoji         *string                `protobuf:"bytes,2,opt,name=emoji,proto3,oneof" json:"emoji,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomStatus) Reset() {
	*x = CustomStatus{}
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomStatus) ProtoMessage() {}

func (x *CustomStatus) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomStatus.ProtoReflect.Descriptor instead.
func (*CustomStatus) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{1}
}

func (x *CustomStatus) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CustomStatus) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

func (x *CustomStatus) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// User activity
type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ActivityType           `protobuf:"varint,1,opt,name=type,proto3,enum=presence.v1.ActivityType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // "Listening to Spotify", "Watching Netflix"
	Details       *string                `protobuf:"bytes,3,opt,name=details,proto3,oneof" json:"details,omitempty"`   // Song name, movie title, etc.
	Url           *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`           // Link to content
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_presence_v1_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{2}
}

func (x *Activity) GetType() ActivityType {
	if x != nil {
		return x.Type
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

func (x *Activity) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Activity) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// Device information
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // "ios", "android", "web", "desktop"
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Status        OnlineStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=presence.v1.OnlineStatus" json:"status,omitempty"`
	LastActiveAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_presence_v1_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{3}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Device) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Device) GetStatus() OnlineStatus {
	if x != nil {
		return x.Status
	}
	return OnlineStatus_ONLINE_STATUS_UNSPECIFIED
}

func (x *Device) GetLastActiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveAt
	}
	return nil
}

// User presence summary (for lists)
type UserPresence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Status        OnlineStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=presence.v1.OnlineStatus" json:"status,omitempty"`
	CustomStatus  *CustomStatus          `protobuf:"bytes,5,opt,name=custom_status,json=customStatus,proto3,oneof" json:"custom_status,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen_at,json=lastSeenAt,proto3,oneof" json:"last_seen_at,omitempty"`
	IsOnline      bool                   `protobuf:"varint,7,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPresence) Reset() {
	*x = UserPresence{}
	mi := &file_presence_v1_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPresence) ProtoMessage() {}

func (x *UserPresence) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPresence.ProtoReflect.Descriptor instead.
func (*UserPresence) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{4}
}

func (x *UserPresence) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPresence) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserPresence) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserPresence) GetStatus() OnlineStatus {
	if x != nil {
		return x.Status
	}
	return OnlineStatus_ONLINE_STATUS_UNSPECIFIED
}

func (x *UserPresence) GetCustomStatus() *CustomStatus {
	if x != nil {
		return x.CustomStatus
	}
	return nil
}

func (x *UserPresence) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *UserPresence) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

// Presence event (for streaming)
type PresenceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "user_online", "user_offline", "status_changed", "activity_changed"
	Presence      *Presence              `protobuf:"bytes,3,opt,name=presence,proto3" json:"presence,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceEvent) Reset() {
	*x = PresenceEvent{}
	mi := &file_presence_v1_presence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceEvent) ProtoMessage() {}

func (x *PresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceEvent.ProtoReflect.Descriptor instead.
func (*PresenceEvent) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{5}
}

func (x *PresenceEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PresenceEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PresenceEvent) GetPresence() *Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *PresenceEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// UpdatePresence (heartbeat)
type UpdatePresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OnlineStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=presence.v1.OnlineStatus" json:"status,omitempty"`
	DeviceId      *string                `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id,omitempty"`
	Activity      *Activity              `protobuf:"bytes,3,opt,name=activity,proto3,oneof" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePresenceRequest) Reset() {
	*x = UpdatePresenceRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePresenceRequest) ProtoMessage() {}

func (x *UpdatePresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePresenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePresenceRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePresenceRequest) GetStatus() OnlineStatus {
	if x != nil {
		return x.Status
	}
	return OnlineStatus_ONLINE_STATUS_UNSPECIFIED
}

func (x *UpdatePresenceRequest) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *UpdatePresenceRequest) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type UpdatePresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      *Presence              `protobuf:"bytes,1,opt,name=presence,proto3" json:"presence,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePresenceResponse) Reset() {
	*x = UpdatePresenceResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePresenceResponse) ProtoMessage() {}

func (x *UpdatePresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePresenceResponse.ProtoReflect.Descriptor instead.
func (*UpdatePresenceResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePresenceResponse) GetPresence() *Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *UpdatePresenceResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetPresence
type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{8}
}

func (x *GetPresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      *Presence              `protobuf:"bytes,1,opt,name=presence,proto3" json:"presence,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{9}
}

func (x *GetPresenceResponse) GetPresence() *Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *GetPresenceResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetBulkPresence
type GetBulkPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // Max 100 users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkPresenceRequest) Reset() {
	*x = GetBulkPresenceRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkPresenceRequest) ProtoMessage() {}

func (x *GetBulkPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetBulkPresenceRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{10}
}

func (x *GetBulkPresenceRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetBulkPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presences     []*Presence            `protobuf:"bytes,1,rep,name=presences,proto3" json:"presences,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkPresenceResponse) Reset() {
	*x = GetBulkPresenceResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkPresenceResponse) ProtoMessage() {}

func (x *GetBulkPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetBulkPresenceResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{11}
}

func (x *GetBulkPresenceResponse) GetPresences() []*Presence {
	if x != nil {
		return x.Presences
	}
	return nil
}

func (x *GetBulkPresenceResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SetStatus
type SetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Emoji         *string                `protobuf:"bytes,2,opt,name=emoji,proto3,oneof" json:"emoji,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusRequest) Reset() {
	*x = SetStatusRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusRequest) ProtoMessage() {}

func (x *SetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusRequest.ProtoReflect.Descriptor instead.
func (*SetStatusRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{12}
}

func (x *SetStatusRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SetStatusRequest) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

func (x *SetStatusRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type SetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *CustomStatus          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusResponse) Reset() {
	*x = SetStatusResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusResponse) ProtoMessage() {}

func (x *SetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusResponse.ProtoReflect.Descriptor instead.
func (*SetStatusResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{13}
}

func (x *SetStatusResponse) GetStatus() *CustomStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SetStatusResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ClearStatus
type ClearStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearStatusRequest) Reset() {
	*x = ClearStatusRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearStatusRequest) ProtoMessage() {}

func (x *ClearStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearStatusRequest.ProtoReflect.Descriptor instead.
func (*ClearStatusRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{14}
}

type ClearStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearStatusResponse) Reset() {
	*x = ClearStatusResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearStatusResponse) ProtoMessage() {}

func (x *ClearStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearStatusResponse.ProtoReflect.Descriptor instead.
func (*ClearStatusResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{15}
}

func (x *ClearStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearStatusResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SetActivity
type SetActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ActivityType           `protobuf:"varint,1,opt,name=type,proto3,enum=presence.v1.ActivityType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Details       *string                `protobuf:"bytes,3,opt,name=details,proto3,oneof" json:"details,omitempty"`
	Url           *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActivityRequest) Reset() {
	*x = SetActivityRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActivityRequest) ProtoMessage() {}

func (x *SetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActivityRequest.ProtoReflect.Descriptor instead.
func (*SetActivityRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{16}
}

func (x *SetActivityRequest) GetType() ActivityType {
	if x != nil {
		return x.Type
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *SetActivityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SetActivityRequest) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

func (x *SetActivityRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type SetActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *Activity              `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActivityResponse) Reset() {
	*x = SetActivityResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActivityResponse) ProtoMessage() {}

func (x *SetActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActivityResponse.ProtoReflect.Descriptor instead.
func (*SetActivityResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{17}
}

func (x *SetActivityResponse) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *SetActivityResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetOnlineUsers
type GetOnlineUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	StatusFilter  *OnlineStatus          `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=presence.v1.OnlineStatus,oneof" json:"status_filter,omitempty"` // Filter by specific status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineUsersRequest) Reset() {
	*x = GetOnlineUsersRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUsersRequest) ProtoMessage() {}

func (x *GetOnlineUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUsersRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineUsersRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{18}
}

func (x *GetOnlineUsersRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetOnlineUsersRequest) GetStatusFilter() OnlineStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return OnlineStatus_ONLINE_STATUS_UNSPECIFIED
}

type GetOnlineUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserPresence        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	TotalOnline   int32                  `protobuf:"varint,3,opt,name=total_online,json=totalOnline,proto3" json:"total_online,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineUsersResponse) Reset() {
	*x = GetOnlineUsersResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUsersResponse) ProtoMessage() {}

func (x *GetOnlineUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUsersResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineUsersResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{19}
}

func (x *GetOnlineUsersResponse) GetUsers() []*UserPresence {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetOnlineUsersResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetOnlineUsersResponse) GetTotalOnline() int32 {
	if x != nil {
		return x.TotalOnline
	}
	return 0
}

func (x *GetOnlineUsersResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StreamPresence
type StreamPresenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Watch specific users (optional, default: all followed users)
	UserIds       []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPresenceRequest) Reset() {
	*x = StreamPresenceRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPresenceRequest) ProtoMessage() {}

func (x *StreamPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPresenceRequest.ProtoReflect.Descriptor instead.
func (*StreamPresenceRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{20}
}

func (x *StreamPresenceRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// PresenceStream (bidirectional)
type PresenceStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*PresenceStreamRequest_Subscribe
	//	*PresenceStreamRequest_Unsubscribe
	//	*PresenceStreamRequest_Heartbeat
	Request       isPresenceStreamRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceStreamRequest) Reset() {
	*x = PresenceStreamRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceStreamRequest) ProtoMessage() {}

func (x *PresenceStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceStreamRequest.ProtoReflect.Descriptor instead.
func (*PresenceStreamRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{21}
}

func (x *PresenceStreamRequest) GetRequest() isPresenceStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PresenceStreamRequest) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Request.(*PresenceStreamRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *PresenceStreamRequest) GetUnsubscribe() *Unsubscribe {
	if x != nil {
		if x, ok := x.Request.(*PresenceStreamRequest_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *PresenceStreamRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Request.(*PresenceStreamRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isPresenceStreamRequest_Request interface {
	isPresenceStreamRequest_Request()
}

type PresenceStreamRequest_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type PresenceStreamRequest_Unsubscribe struct {
	Unsubscribe *Unsubscribe `protobuf:"bytes,2,opt,name=unsubscribe,proto3,oneof"`
}

type PresenceStreamRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*PresenceStreamRequest_Subscribe) isPresenceStreamRequest_Request() {}

func (*PresenceStreamRequest_Unsubscribe) isPresenceStreamRequest_Request() {}

func (*PresenceStreamRequest_Heartbeat) isPresenceStreamRequest_Request() {}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_presence_v1_presence_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{22}
}

func (x *Subscribe) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_presence_v1_presence_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{23}
}

func (x *Unsubscribe) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OnlineStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=presence.v1.OnlineStatus" json:"status,omitempty"`
	Activity      *Activity              `protobuf:"bytes,2,opt,name=activity,proto3,oneof" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_presence_v1_presence_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{24}
}

func (x *Heartbeat) GetStatus() OnlineStatus {
	if x != nil {
		return x.Status
	}
	return OnlineStatus_ONLINE_STATUS_UNSPECIFIED
}

func (x *Heartbeat) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type PresenceStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*PresenceStreamResponse_PresenceEvent
	//	*PresenceStreamResponse_SubscriptionConfirmation
	//	*PresenceStreamResponse_HeartbeatAck
	Response      isPresenceStreamResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceStreamResponse) Reset() {
	*x = PresenceStreamResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceStreamResponse) ProtoMessage() {}

func (x *PresenceStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceStreamResponse.ProtoReflect.Descriptor instead.
func (*PresenceStreamResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{25}
}

func (x *PresenceStreamResponse) GetResponse() isPresenceStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PresenceStreamResponse) GetPresenceEvent() *PresenceEvent {
	if x != nil {
		if x, ok := x.Response.(*PresenceStreamResponse_PresenceEvent); ok {
			return x.PresenceEvent
		}
	}
	return nil
}

func (x *PresenceStreamResponse) GetSubscriptionConfirmation() *SubscriptionConfirmation {
	if x != nil {
		if x, ok := x.Response.(*PresenceStreamResponse_SubscriptionConfirmation); ok {
			return x.SubscriptionConfirmation
		}
	}
	return nil
}

func (x *PresenceStreamResponse) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Response.(*PresenceStreamResponse_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

type isPresenceStreamResponse_Response interface {
	isPresenceStreamResponse_Response()
}

type PresenceStreamResponse_PresenceEvent struct {
	PresenceEvent *PresenceEvent `protobuf:"bytes,1,opt,name=presence_event,json=presenceEvent,proto3,oneof"`
}

type PresenceStreamResponse_SubscriptionConfirmation struct {
	SubscriptionConfirmation *SubscriptionConfirmation `protobuf:"bytes,2,opt,name=subscription_confirmation,json=subscriptionConfirmation,proto3,oneof"`
}

type PresenceStreamResponse_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,3,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

func (*PresenceStreamResponse_PresenceEvent) isPresenceStreamResponse_Response() {}

func (*PresenceStreamResponse_SubscriptionConfirmation) isPresenceStreamResponse_Response() {}

func (*PresenceStreamResponse_HeartbeatAck) isPresenceStreamResponse_Response() {}

type SubscriptionConfirmation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserIds         []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	SubscribedCount int32                  `protobuf:"varint,2,opt,name=subscribed_count,json=subscribedCount,proto3" json:"subscribed_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscriptionConfirmation) Reset() {
	*x = SubscriptionConfirmation{}
	mi := &file_presence_v1_presence_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionConfirmation) ProtoMessage() {}

func (x *SubscriptionConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionConfirmation.ProtoReflect.Descriptor instead.
func (*SubscriptionConfirmation) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{26}
}

func (x *SubscriptionConfirmation) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SubscriptionConfirmation) GetSubscribedCount() int32 {
	if x != nil {
		return x.SubscribedCount
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_presence_v1_presence_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{27}
}

func (x *HeartbeatAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_presence_v1_presence_proto protoreflect.FileDescriptor

const file_presence_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x1apresence/v1/presence.proto\x12\vpresence.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\xe4\x03\n" +
	"\bPresence\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.presence.v1.OnlineStatusR\x06status\x12<\n" +
	"\flast_seen_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12C\n" +
	"\rcustom_status\x18\x04 \x01(\v2\x19.presence.v1.CustomStatusH\x00R\fcustomStatus\x88\x01\x01\x126\n" +
	"\bactivity\x18\x05 \x01(\v2\x15.presence.v1.ActivityH\x01R\bactivity\x88\x01\x01\x12-\n" +
	"\adevices\x18\x06 \x03(\v2\x13.presence.v1.DeviceR\adevices\x12>\n" +
	"\n" +
	"idle_since\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tidleSince\x88\x01\x01\x12\x1b\n" +
	"\tis_online\x18\b \x01(\bR\bisOnline\x12\x17\n" +
	"\ais_away\x18\t \x01(\bR\x06isAwayB\x10\n" +
	"\x0e_custom_statusB\v\n" +
	"\t_activityB\r\n" +
	"\v_idle_since\"\x96\x01\n" +
	"\fCustomStatus\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\x05emoji\x18\x02 \x01(\tH\x00R\x05emoji\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\texpiresAt\x88\x01\x01B\b\n" +
	"\x06_emojiB\r\n" +
	"\v_expires_at\"\xe0\x01\n" +
	"\bActivity\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.presence.v1.ActivityTypeR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\adetails\x18\x03 \x01(\tH\x00R\adetails\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x01R\x03url\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAtB\n" +
	"\n" +
	"\b_detailsB\x06\n" +
	"\x04_url\"\xd7\x01\n" +
	"\x06Device\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.presence.v1.OnlineStatusR\x06status\x12@\n" +
	"\x0elast_active_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastActiveAt\"\xdd\x02\n" +
	"\fUserPresence\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.presence.v1.OnlineStatusR\x06status\x12C\n" +
	"\rcustom_status\x18\x05 \x01(\v2\x19.presence.v1.CustomStatusH\x00R\fcustomStatus\x88\x01\x01\x12A\n" +
	"\flast_seen_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"lastSeenAt\x88\x01\x01\x12\x1b\n" +
	"\tis_online\x18\a \x01(\bR\bisOnlineB\x10\n" +
	"\x0e_custom_statusB\x0f\n" +
	"\r_last_seen_at\"\xb6\x01\n" +
	"\rPresenceEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x121\n" +
	"\bpresence\x18\x03 \x01(\v2\x15.presence.v1.PresenceR\bpresence\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xbf\x01\n" +
	"\x15UpdatePresenceRequest\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.presence.v1.OnlineStatusR\x06status\x12 \n" +
	"\tdevice_id\x18\x02 \x01(\tH\x00R\bdeviceId\x88\x01\x01\x126\n" +
	"\bactivity\x18\x03 \x01(\v2\x15.presence.v1.ActivityH\x01R\bactivity\x88\x01\x01B\f\n" +
	"\n" +
	"_device_idB\v\n" +
	"\t_activity\"\x84\x01\n" +
	"\x16UpdatePresenceResponse\x121\n" +
	"\bpresence\x18\x01 \x01(\v2\x15.presence.v1.PresenceR\bpresence\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"-\n" +
	"\x12GetPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x81\x01\n" +
	"\x13GetPresenceResponse\x121\n" +
	"\bpresence\x18\x01 \x01(\v2\x15.presence.v1.PresenceR\bpresence\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"3\n" +
	"\x16GetBulkPresenceRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\x87\x01\n" +
	"\x17GetBulkPresenceResponse\x123\n" +
	"\tpresences\x18\x01 \x03(\v2\x15.presence.v1.PresenceR\tpresences\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x9a\x01\n" +
	"\x10SetStatusRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\x05emoji\x18\x02 \x01(\tH\x00R\x05emoji\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\texpiresAt\x88\x01\x01B\b\n" +
	"\x06_emojiB\r\n" +
	"\v_expires_at\"\x7f\n" +
	"\x11SetStatusResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.presence.v1.CustomStatusR\x06status\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x14\n" +
	"\x12ClearStatusRequest\"h\n" +
	"\x13ClearStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\xaf\x01\n" +
	"\x12SetActivityRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.presence.v1.ActivityTypeR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\adetails\x18\x03 \x01(\tH\x00R\adetails\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x01R\x03url\x88\x01\x01B\n" +
	"\n" +
	"\b_detailsB\x06\n" +
	"\x04_url\"\x81\x01\n" +
	"\x13SetActivityResponse\x121\n" +
	"\bactivity\x18\x01 \x01(\v2\x15.presence.v1.ActivityR\bactivity\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\xac\x01\n" +
	"\x15GetOnlineUsersRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12C\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x19.presence.v1.OnlineStatusH\x00R\fstatusFilter\x88\x01\x01B\x10\n" +
	"\x0e_status_filter\"\xe4\x01\n" +
	"\x16GetOnlineUsersResponse\x12/\n" +
	"\x05users\x18\x01 \x03(\v2\x19.presence.v1.UserPresenceR\x05users\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\x12!\n" +
	"\ftotal_online\x18\x03 \x01(\x05R\vtotalOnline\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"2\n" +
	"\x15StreamPresenceRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xd0\x01\n" +
	"\x15PresenceStreamRequest\x126\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x16.presence.v1.SubscribeH\x00R\tsubscribe\x12<\n" +
	"\vunsubscribe\x18\x02 \x01(\v2\x18.presence.v1.UnsubscribeH\x00R\vunsubscribe\x126\n" +
	"\theartbeat\x18\x03 \x01(\v2\x16.presence.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\arequest\"&\n" +
	"\tSubscribe\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"(\n" +
	"\vUnsubscribe\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\x83\x01\n" +
	"\tHeartbeat\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.presence.v1.OnlineStatusR\x06status\x126\n" +
	"\bactivity\x18\x02 \x01(\v2\x15.presence.v1.ActivityH\x00R\bactivity\x88\x01\x01B\v\n" +
	"\t_activity\"\x91\x02\n" +
	"\x16PresenceStreamResponse\x12C\n" +
	"\x0epresence_event\x18\x01 \x01(\v2\x1a.presence.v1.PresenceEventH\x00R\rpresenceEvent\x12d\n" +
	"\x19subscription_confirmation\x18\x02 \x01(\v2%.presence.v1.SubscriptionConfirmationH\x00R\x18subscriptionConfirmation\x12@\n" +
	"\rheartbeat_ack\x18\x03 \x01(\v2\x19.presence.v1.HeartbeatAckH\x00R\fheartbeatAckB\n" +
	"\n" +
	"\bresponse\"`\n" +
	"\x18SubscriptionConfirmation\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12)\n" +
	"\x10subscribed_count\x18\x02 \x01(\x05R\x0fsubscribedCount\"K\n" +
	"\fHeartbeatAck\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime*\xaf\x01\n" +
	"\fOnlineStatus\x12\x1d\n" +
	"\x19ONLINE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ONLINE_STATUS_ONLINE\x10\x01\x12\x16\n" +
	"\x12ONLINE_STATUS_AWAY\x10\x02\x12\x16\n" +
	"\x12ONLINE_STATUS_BUSY\x10\x03\x12\x19\n" +
	"\x15ONLINE_STATUS_OFFLINE\x10\x04\x12\x1b\n" +
	"\x17ONLINE_STATUS_INVISIBLE\x10\x05*\xef\x01\n" +
	"\fActivityType\x12\x1d\n" +
	"\x19ACTIVITY_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACTIVITY_TYPE_BROWSING\x10\x01\x12\x18\n" +
	"\x14ACTIVITY_TYPE_TYPING\x10\x02\x12\x1b\n" +
	"\x17ACTIVITY_TYPE_RECORDING\x10\x03\x12\x19\n" +
	"\x15ACTIVITY_TYPE_IN_CALL\x10\x04\x12\x19\n" +
	"\x15ACTIVITY_TYPE_PLAYING\x10\x05\x12\x1b\n" +
	"\x17ACTIVITY_TYPE_LISTENING\x10\x06\x12\x1a\n" +
	"\x16ACTIVITY_TYPE_WATCHING\x10\a2\x8a\b\n" +
	"\x0fPresenceService\x12r\n" +
	"\x0eUpdatePresence\x12\".presence.v1.UpdatePresenceRequest\x1a#.presence.v1.UpdatePresenceResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/presence\x12p\n" +
	"\vGetPresence\x12\x1f.presence.v1.GetPresenceRequest\x1a .presence.v1.GetPresenceResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/presence/{user_id}\x12z\n" +
	"\x0fGetBulkPresence\x12#.presence.v1.GetBulkPresenceRequest\x1a$.presence.v1.GetBulkPresenceResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/presence/bulk\x12j\n" +
	"\tSetStatus\x12\x1d.presence.v1.SetStatusRequest\x1a\x1e.presence.v1.SetStatusResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/presence/status\x12m\n" +
	"\vClearStatus\x12\x1f.presence.v1.ClearStatusRequest\x1a .presence.v1.ClearStatusResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/presence/status\x12r\n" +
	"\vSetActivity\x12\x1f.presence.v1.SetActivityRequest\x1a .presence.v1.SetActivityResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/presence/activity\x12v\n" +
	"\x0eGetOnlineUsers\x12\".presence.v1.GetOnlineUsersRequest\x1a#.presence.v1.GetOnlineUsersResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/presence/online\x12o\n" +
	"\x0eStreamPresence\x12\".presence.v1.StreamPresenceRequest\x1a\x1a.presence.v1.PresenceEvent\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/presence/stream0\x01\x12]\n" +
	"\x0ePresenceStream\x12\".presence.v1.PresenceStreamRequest\x1a#.presence.v1.PresenceStreamResponse(\x010\x01B\x9f\x01\n" +
	"\x0fcom.presence.v1B\rPresenceProtoP\x01Z0github.com/0xsj/nexus/api/presence/v1;presencev1\xa2\x02\x03PXX\xaa\x02\vPresence.V1\xca\x02\vPresence\\V1\xe2\x02\x17Presence\\V1\\GPBMetadata\xea\x02\fPresence::V1b\x06proto3"

var (
	file_presence_v1_presence_proto_rawDescOnce sync.Once
	file_presence_v1_presence_proto_rawDescData []byte
)

func file_presence_v1_presence_proto_rawDescGZIP() []byte {
	file_presence_v1_presence_proto_rawDescOnce.Do(func() {
		file_presence_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)))
	})
	return file_presence_v1_presence_proto_rawDescData
}

var file_presence_v1_presence_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_presence_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_presence_v1_presence_proto_goTypes = []any{
	(OnlineStatus)(0),                // 0: presence.v1.OnlineStatus
	(ActivityType)(0),                // 1: presence.v1.ActivityType
	(*Presence)(nil),                 // 2: presence.v1.Presence
	(*CustomStatus)(nil),             // 3: presence.v1.CustomStatus
	(*Activity)(nil),                 // 4: presence.v1.Activity
	(*Device)(nil),                   // 5: presence.v1.Device
	(*UserPresence)(nil),             // 6: presence.v1.UserPresence
	(*PresenceEvent)(nil),            // 7: presence.v1.PresenceEvent
	(*UpdatePresenceRequest)(nil),    // 8: presence.v1.UpdatePresenceRequest
	(*UpdatePresenceResponse)(nil),   // 9: presence.v1.UpdatePresenceResponse
	(*GetPresenceRequest)(nil),       // 10: presence.v1.GetPresenceRequest
	(*GetPresenceResponse)(nil),      // 11: presence.v1.GetPresenceResponse
	(*GetBulkPresenceRequest)(nil),   // 12: presence.v1.GetBulkPresenceRequest
	(*GetBulkPresenceResponse)(nil),  // 13: presence.v1.GetBulkPresenceResponse
	(*SetStatusRequest)(nil),         // 14: presence.v1.SetStatusRequest
	(*SetStatusResponse)(nil),        // 15: presence.v1.SetStatusResponse
	(*ClearStatusRequest)(nil),       // 16: presence.v1.ClearStatusRequest
	(*ClearStatusResponse)(nil),      // 17: presence.v1.ClearStatusResponse
	(*SetActivityRequest)(nil),       // 18: presence.v1.SetActivityRequest
	(*SetActivityResponse)(nil),      // 19: presence.v1.SetActivityResponse
	(*GetOnlineUsersRequest)(nil),    // 20: presence.v1.GetOnlineUsersRequest
	(*GetOnlineUsersResponse)(nil),   // 21: presence.v1.GetOnlineUsersResponse
	(*StreamPresenceRequest)(nil),    // 22: presence.v1.StreamPresenceRequest
	(*PresenceStreamRequest)(nil),    // 23: presence.v1.PresenceStreamRequest
	(*Subscribe)(nil),                // 24: presence.v1.Subscribe
	(*Unsubscribe)(nil),              // 25: presence.v1.Unsubscribe
	(*Heartbeat)(nil),                // 26: presence.v1.Heartbeat
	(*PresenceStreamResponse)(nil),   // 27: presence.v1.PresenceStreamResponse
	(*SubscriptionConfirmation)(nil), // 28: presence.v1.SubscriptionConfirmation
	(*HeartbeatAck)(nil),             // 29: presence.v1.HeartbeatAck
	(*timestamppb.Timestamp)(nil),    // 30: google.protobuf.Timestamp
	(*v1.ResponseMetadata)(nil),      // 31: common.v1.ResponseMetadata
	(*v1.PaginationRequest)(nil),     // 32: common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),    // 33: common.v1.PaginationResponse
}
var file_presence_v1_presence_proto_depIdxs = []int32{
	0,  // 0: presence.v1.Presence.status:type_name -> presence.v1.OnlineStatus
	30, // 1: presence.v1.Presence.last_seen_at:type_name -> google.protobuf.Timestamp
	3,  // 2: presence.v1.Presence.custom_status:type_name -> presence.v1.CustomStatus
	4,  // 3: presence.v1.Presence.activity:type_name -> presence.v1.Activity
	5,  // 4: presence.v1.Presence.devices:type_name -> presence.v1.Device
	30, // 5: presence.v1.Presence.idle_since:type_name -> google.protobuf.Timestamp
	30, // 6: presence.v1.CustomStatus.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 7: presence.v1.Activity.type:type_name -> presence.v1.ActivityType
	30, // 8: presence.v1.Activity.started_at:type_name -> google.protobuf.Timestamp
	0,  // 9: presence.v1.Device.status:type_name -> presence.v1.OnlineStatus
	30, // 10: presence.v1.Device.last_active_at:type_name -> google.protobuf.Timestamp
	0,  // 11: presence.v1.UserPresence.status:type_name -> presence.v1.OnlineStatus
	3,  // 12: presence.v1.UserPresence.custom_status:type_name -> presence.v1.CustomStatus
	30, // 13: presence.v1.UserPresence.last_seen_at:type_name -> google.protobuf.Timestamp
	2,  // 14: presence.v1.PresenceEvent.presence:type_name -> presence.v1.Presence
	30, // 15: presence.v1.PresenceEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 16: presence.v1.UpdatePresenceRequest.status:type_name -> presence.v1.OnlineStatus
	4,  // 17: presence.v1.UpdatePresenceRequest.activity:type_name -> presence.v1.Activity
	2,  // 18: presence.v1.UpdatePresenceResponse.presence:type_name -> presence.v1.Presence
	31, // 19: presence.v1.UpdatePresenceResponse.metadata:type_name -> common.v1.ResponseMetadata
	2,  // 20: presence.v1.GetPresenceResponse.presence:type_name -> presence.v1.Presence
	31, // 21: presence.v1.GetPresenceResponse.metadata:type_name -> common.v1.ResponseMetadata
	2,  // 22: presence.v1.GetBulkPresenceResponse.presences:type_name -> presence.v1.Presence
	31, // 23: presence.v1.GetBulkPresenceResponse.metadata:type_name -> common.v1.ResponseMetadata
	30, // 24: presence.v1.SetStatusRequest.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 25: presence.v1.SetStatusResponse.status:type_name -> presence.v1.CustomStatus
	31, // 26: presence.v1.SetStatusResponse.metadata:type_name -> common.v1.ResponseMetadata
	31, // 27: presence.v1.ClearStatusResponse.metadata:type_name -> common.v1.ResponseMetadata
	1,  // 28: presence.v1.SetActivityRequest.type:type_name -> presence.v1.ActivityType
	4,  // 29: presence.v1.SetActivityResponse.activity:type_name -> presence.v1.Activity
	31, // 30: presence.v1.SetActivityResponse.metadata:type_name -> common.v1.ResponseMetadata
	32, // 31: presence.v1.GetOnlineUsersRequest.pagination:type_name -> common.v1.PaginationRequest
	0,  // 32: presence.v1.GetOnlineUsersRequest.status_filter:type_name -> presence.v1.OnlineStatus
	6,  // 33: presence.v1.GetOnlineUsersResponse.users:type_name -> presence.v1.UserPresence
	33, // 34: presence.v1.GetOnlineUsersResponse.pagination:type_name -> common.v1.PaginationResponse
	31, // 35: presence.v1.GetOnlineUsersResponse.metadata:type_name -> common.v1.ResponseMetadata
	24, // 36: presence.v1.PresenceStreamRequest.subscribe:type_name -> presence.v1.Subscribe
	25, // 37: presence.v1.PresenceStreamRequest.unsubscribe:type_name -> presence.v1.Unsubscribe
	26, // 38: presence.v1.PresenceStreamRequest.heartbeat:type_name -> presence.v1.Heartbeat
	0,  // 39: presence.v1.Heartbeat.status:type_name -> presence.v1.OnlineStatus
	4,  // 40: presence.v1.Heartbeat.activity:type_name -> presence.v1.Activity
	7,  // 41: presence.v1.PresenceStreamResponse.presence_event:type_name -> presence.v1.PresenceEvent
	28, // 42: presence.v1.PresenceStreamResponse.subscription_confirmation:type_name -> presence.v1.SubscriptionConfirmation
	29, // 43: presence.v1.PresenceStreamResponse.heartbeat_ack:type_name -> presence.v1.HeartbeatAck
	30, // 44: presence.v1.HeartbeatAck.server_time:type_name -> google.protobuf.Timestamp
	8,  // 45: presence.v1.PresenceService.UpdatePresence:input_type -> presence.v1.UpdatePresenceRequest
	10, // 46: presence.v1.PresenceService.GetPresence:input_type -> presence.v1.GetPresenceRequest
	12, // 47: presence.v1.PresenceService.GetBulkPresence:input_type -> presence.v1.GetBulkPresenceRequest
	14, // 48: presence.v1.PresenceService.SetStatus:input_type -> presence.v1.SetStatusRequest
	16, // 49: presence.v1.PresenceService.ClearStatus:input_type -> presence.v1.ClearStatusRequest
	18, // 50: presence.v1.PresenceService.SetActivity:input_type -> presence.v1.SetActivityRequest
	20, // 51: presence.v1.PresenceService.GetOnlineUsers:input_type -> presence.v1.GetOnlineUsersRequest
	22, // 52: presence.v1.PresenceService.StreamPresence:input_type -> presence.v1.StreamPresenceRequest
	23, // 53: presence.v1.PresenceService.PresenceStream:input_type -> presence.v1.PresenceStreamRequest
	9,  // 54: presence.v1.PresenceService.UpdatePresence:output_type -> presence.v1.UpdatePresenceResponse
	11, // 55: presence.v1.PresenceService.GetPresence:output_type -> presence.v1.GetPresenceResponse
	13, // 56: presence.v1.PresenceService.GetBulkPresence:output_type -> presence.v1.GetBulkPresenceResponse
	15, // 57: presence.v1.PresenceService.SetStatus:output_type -> presence.v1.SetStatusResponse
	17, // 58: presence.v1.PresenceService.ClearStatus:output_type -> presence.v1.ClearStatusResponse
	19, // 59: presence.v1.PresenceService.SetActivity:output_type -> presence.v1.SetActivityResponse
	21, // 60: presence.v1.PresenceService.GetOnlineUsers:output_type -> presence.v1.GetOnlineUsersResponse
	7,  // 61: presence.v1.PresenceService.StreamPresence:output_type -> presence.v1.PresenceEvent
	27, // 62: presence.v1.PresenceService.PresenceStream:output_type -> presence.v1.PresenceStreamResponse
	54, // [54:63] is the sub-list for method output_type
	45, // [45:54] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_presence_v1_presence_proto_init() }
func file_presence_v1_presence_proto_init() {
	if File_presence_v1_presence_proto != nil {
		return
	}
	file_presence_v1_presence_proto_msgTypes[0].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[1].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[2].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[4].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[6].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[12].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[16].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[18].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[21].OneofWrappers = []any{
		(*PresenceStreamRequest_Subscribe)(nil),
		(*PresenceStreamRequest_Unsubscribe)(nil),
		(*PresenceStreamRequest_Heartbeat)(nil),
	}
	file_presence_v1_presence_proto_msgTypes[24].OneofWrappers = []any{}
	file_presence_v1_presence_proto_msgTypes[25].OneofWrappers = []any{
		(*PresenceStreamResponse_PresenceEvent)(nil),
		(*PresenceStreamResponse_SubscriptionConfirmation)(nil),
		(*PresenceStreamResponse_HeartbeatAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_v1_presence_proto_goTypes,
		DependencyIndexes: file_presence_v1_presence_proto_depIdxs,
		EnumInfos:         file_presence_v1_presence_proto_enumTypes,
		MessageInfos:      file_presence_v1_presence_proto_msgTypes,
	}.Build()
	File_presence_v1_presence_proto = out.File
	file_presence_v1_presence_proto_goTypes = nil
	file_presence_v1_presence_proto_depIdxs = nil
}
