// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: social/v1/social.proto

package socialv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialService_FollowUser_FullMethodName           = "/social.v1.SocialService/FollowUser"
	SocialService_UnfollowUser_FullMethodName         = "/social.v1.SocialService/UnfollowUser"
	SocialService_GetFollowers_FullMethodName         = "/social.v1.SocialService/GetFollowers"
	SocialService_GetFollowing_FullMethodName         = "/social.v1.SocialService/GetFollowing"
	SocialService_GetMutualFollowers_FullMethodName   = "/social.v1.SocialService/GetMutualFollowers"
	SocialService_CheckFollowStatus_FullMethodName    = "/social.v1.SocialService/CheckFollowStatus"
	SocialService_GetFollowSuggestions_FullMethodName = "/social.v1.SocialService/GetFollowSuggestions"
	SocialService_BlockUser_FullMethodName            = "/social.v1.SocialService/BlockUser"
	SocialService_UnblockUser_FullMethodName          = "/social.v1.SocialService/UnblockUser"
	SocialService_GetBlockedUsers_FullMethodName      = "/social.v1.SocialService/GetBlockedUsers"
	SocialService_MuteUser_FullMethodName             = "/social.v1.SocialService/MuteUser"
	SocialService_UnmuteUser_FullMethodName           = "/social.v1.SocialService/UnmuteUser"
	SocialService_GetMutedUsers_FullMethodName        = "/social.v1.SocialService/GetMutedUsers"
	SocialService_StreamFollowEvents_FullMethodName   = "/social.v1.SocialService/StreamFollowEvents"
)

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Social service handles follow/unfollow and social graph
type SocialServiceClient interface {
	// Follow a user
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error)
	// Unfollow a user
	UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error)
	// Get followers of a user
	GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error)
	// Get users that a user is following
	GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error)
	// Get mutual followers (friends)
	GetMutualFollowers(ctx context.Context, in *GetMutualFollowersRequest, opts ...grpc.CallOption) (*GetMutualFollowersResponse, error)
	// Check if user A follows user B
	CheckFollowStatus(ctx context.Context, in *CheckFollowStatusRequest, opts ...grpc.CallOption) (*CheckFollowStatusResponse, error)
	// Get follow suggestions (who to follow)
	GetFollowSuggestions(ctx context.Context, in *GetFollowSuggestionsRequest, opts ...grpc.CallOption) (*GetFollowSuggestionsResponse, error)
	// Block a user
	BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*BlockUserResponse, error)
	// Unblock a user
	UnblockUser(ctx context.Context, in *UnblockUserRequest, opts ...grpc.CallOption) (*UnblockUserResponse, error)
	// Get blocked users
	GetBlockedUsers(ctx context.Context, in *GetBlockedUsersRequest, opts ...grpc.CallOption) (*GetBlockedUsersResponse, error)
	// Mute a user (hide their content without unfollowing)
	MuteUser(ctx context.Context, in *MuteUserRequest, opts ...grpc.CallOption) (*MuteUserResponse, error)
	// Unmute a user
	UnmuteUser(ctx context.Context, in *UnmuteUserRequest, opts ...grpc.CallOption) (*UnmuteUserResponse, error)
	// Get muted users
	GetMutedUsers(ctx context.Context, in *GetMutedUsersRequest, opts ...grpc.CallOption) (*GetMutedUsersResponse, error)
	// Stream follow events (real-time notifications when someone follows/unfollows)
	StreamFollowEvents(ctx context.Context, in *StreamFollowEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FollowEvent], error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowUserResponse)
	err := c.cc.Invoke(ctx, SocialService_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowUserResponse)
	err := c.cc.Invoke(ctx, SocialService_UnfollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowersResponse)
	err := c.cc.Invoke(ctx, SocialService_GetFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingResponse)
	err := c.cc.Invoke(ctx, SocialService_GetFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetMutualFollowers(ctx context.Context, in *GetMutualFollowersRequest, opts ...grpc.CallOption) (*GetMutualFollowersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMutualFollowersResponse)
	err := c.cc.Invoke(ctx, SocialService_GetMutualFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) CheckFollowStatus(ctx context.Context, in *CheckFollowStatusRequest, opts ...grpc.CallOption) (*CheckFollowStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFollowStatusResponse)
	err := c.cc.Invoke(ctx, SocialService_CheckFollowStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetFollowSuggestions(ctx context.Context, in *GetFollowSuggestionsRequest, opts ...grpc.CallOption) (*GetFollowSuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowSuggestionsResponse)
	err := c.cc.Invoke(ctx, SocialService_GetFollowSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*BlockUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockUserResponse)
	err := c.cc.Invoke(ctx, SocialService_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) UnblockUser(ctx context.Context, in *UnblockUserRequest, opts ...grpc.CallOption) (*UnblockUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockUserResponse)
	err := c.cc.Invoke(ctx, SocialService_UnblockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetBlockedUsers(ctx context.Context, in *GetBlockedUsersRequest, opts ...grpc.CallOption) (*GetBlockedUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockedUsersResponse)
	err := c.cc.Invoke(ctx, SocialService_GetBlockedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) MuteUser(ctx context.Context, in *MuteUserRequest, opts ...grpc.CallOption) (*MuteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MuteUserResponse)
	err := c.cc.Invoke(ctx, SocialService_MuteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) UnmuteUser(ctx context.Context, in *UnmuteUserRequest, opts ...grpc.CallOption) (*UnmuteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmuteUserResponse)
	err := c.cc.Invoke(ctx, SocialService_UnmuteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetMutedUsers(ctx context.Context, in *GetMutedUsersRequest, opts ...grpc.CallOption) (*GetMutedUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMutedUsersResponse)
	err := c.cc.Invoke(ctx, SocialService_GetMutedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) StreamFollowEvents(ctx context.Context, in *StreamFollowEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FollowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SocialService_ServiceDesc.Streams[0], SocialService_StreamFollowEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFollowEventsRequest, FollowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SocialService_StreamFollowEventsClient = grpc.ServerStreamingClient[FollowEvent]

// SocialServiceServer is the server API for SocialService service.
// All implementations must embed UnimplementedSocialServiceServer
// for forward compatibility.
//
// Social service handles follow/unfollow and social graph
type SocialServiceServer interface {
	// Follow a user
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error)
	// Unfollow a user
	UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error)
	// Get followers of a user
	GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error)
	// Get users that a user is following
	GetFollowing(context.Context, *GetFollowingRequest) (*GetFollowingResponse, error)
	// Get mutual followers (friends)
	GetMutualFollowers(context.Context, *GetMutualFollowersRequest) (*GetMutualFollowersResponse, error)
	// Check if user A follows user B
	CheckFollowStatus(context.Context, *CheckFollowStatusRequest) (*CheckFollowStatusResponse, error)
	// Get follow suggestions (who to follow)
	GetFollowSuggestions(context.Context, *GetFollowSuggestionsRequest) (*GetFollowSuggestionsResponse, error)
	// Block a user
	BlockUser(context.Context, *BlockUserRequest) (*BlockUserResponse, error)
	// Unblock a user
	UnblockUser(context.Context, *UnblockUserRequest) (*UnblockUserResponse, error)
	// Get blocked users
	GetBlockedUsers(context.Context, *GetBlockedUsersRequest) (*GetBlockedUsersResponse, error)
	// Mute a user (hide their content without unfollowing)
	MuteUser(context.Context, *MuteUserRequest) (*MuteUserResponse, error)
	// Unmute a user
	UnmuteUser(context.Context, *UnmuteUserRequest) (*UnmuteUserResponse, error)
	// Get muted users
	GetMutedUsers(context.Context, *GetMutedUsersRequest) (*GetMutedUsersResponse, error)
	// Stream follow events (real-time notifications when someone follows/unfollows)
	StreamFollowEvents(*StreamFollowEventsRequest, grpc.ServerStreamingServer[FollowEvent]) error
	mustEmbedUnimplementedSocialServiceServer()
}

// UnimplementedSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServiceServer struct{}

func (UnimplementedSocialServiceServer) FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedSocialServiceServer) UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedSocialServiceServer) GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (UnimplementedSocialServiceServer) GetFollowing(context.Context, *GetFollowingRequest) (*GetFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowing not implemented")
}
func (UnimplementedSocialServiceServer) GetMutualFollowers(context.Context, *GetMutualFollowersRequest) (*GetMutualFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMutualFollowers not implemented")
}
func (UnimplementedSocialServiceServer) CheckFollowStatus(context.Context, *CheckFollowStatusRequest) (*CheckFollowStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFollowStatus not implemented")
}
func (UnimplementedSocialServiceServer) GetFollowSuggestions(context.Context, *GetFollowSuggestionsRequest) (*GetFollowSuggestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowSuggestions not implemented")
}
func (UnimplementedSocialServiceServer) BlockUser(context.Context, *BlockUserRequest) (*BlockUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockUser not implemented")
}
func (UnimplementedSocialServiceServer) UnblockUser(context.Context, *UnblockUserRequest) (*UnblockUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockUser not implemented")
}
func (UnimplementedSocialServiceServer) GetBlockedUsers(context.Context, *GetBlockedUsersRequest) (*GetBlockedUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockedUsers not implemented")
}
func (UnimplementedSocialServiceServer) MuteUser(context.Context, *MuteUserRequest) (*MuteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MuteUser not implemented")
}
func (UnimplementedSocialServiceServer) UnmuteUser(context.Context, *UnmuteUserRequest) (*UnmuteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmuteUser not implemented")
}
func (UnimplementedSocialServiceServer) GetMutedUsers(context.Context, *GetMutedUsersRequest) (*GetMutedUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMutedUsers not implemented")
}
func (UnimplementedSocialServiceServer) StreamFollowEvents(*StreamFollowEventsRequest, grpc.ServerStreamingServer[FollowEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamFollowEvents not implemented")
}
func (UnimplementedSocialServiceServer) mustEmbedUnimplementedSocialServiceServer() {}
func (UnimplementedSocialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServiceServer will
// result in compilation errors.
type UnsafeSocialServiceServer interface {
	mustEmbedUnimplementedSocialServiceServer()
}

func RegisterSocialServiceServer(s grpc.ServiceRegistrar, srv SocialServiceServer) {
	// If the following call pancis, it indicates UnimplementedSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialService_ServiceDesc, srv)
}

func _SocialService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).UnfollowUser(ctx, req.(*UnfollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetFollowers(ctx, req.(*GetFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetFollowing(ctx, req.(*GetFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetMutualFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMutualFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetMutualFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetMutualFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetMutualFollowers(ctx, req.(*GetMutualFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_CheckFollowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFollowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).CheckFollowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_CheckFollowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).CheckFollowStatus(ctx, req.(*CheckFollowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetFollowSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetFollowSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetFollowSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetFollowSuggestions(ctx, req.(*GetFollowSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).BlockUser(ctx, req.(*BlockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_UnblockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).UnblockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_UnblockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).UnblockUser(ctx, req.(*UnblockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetBlockedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockedUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetBlockedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetBlockedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetBlockedUsers(ctx, req.(*GetBlockedUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_MuteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).MuteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_MuteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).MuteUser(ctx, req.(*MuteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_UnmuteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmuteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).UnmuteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_UnmuteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).UnmuteUser(ctx, req.(*UnmuteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetMutedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMutedUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetMutedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetMutedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetMutedUsers(ctx, req.(*GetMutedUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_StreamFollowEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFollowEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SocialServiceServer).StreamFollowEvents(m, &grpc.GenericServerStream[StreamFollowEventsRequest, FollowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SocialService_StreamFollowEventsServer = grpc.ServerStreamingServer[FollowEvent]

// SocialService_ServiceDesc is the grpc.ServiceDesc for SocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.v1.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowUser",
			Handler:    _SocialService_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _SocialService_UnfollowUser_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _SocialService_GetFollowers_Handler,
		},
		{
			MethodName: "GetFollowing",
			Handler:    _SocialService_GetFollowing_Handler,
		},
		{
			MethodName: "GetMutualFollowers",
			Handler:    _SocialService_GetMutualFollowers_Handler,
		},
		{
			MethodName: "CheckFollowStatus",
			Handler:    _SocialService_CheckFollowStatus_Handler,
		},
		{
			MethodName: "GetFollowSuggestions",
			Handler:    _SocialService_GetFollowSuggestions_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _SocialService_BlockUser_Handler,
		},
		{
			MethodName: "UnblockUser",
			Handler:    _SocialService_UnblockUser_Handler,
		},
		{
			MethodName: "GetBlockedUsers",
			Handler:    _SocialService_GetBlockedUsers_Handler,
		},
		{
			MethodName: "MuteUser",
			Handler:    _SocialService_MuteUser_Handler,
		},
		{
			MethodName: "UnmuteUser",
			Handler:    _SocialService_UnmuteUser_Handler,
		},
		{
			MethodName: "GetMutedUsers",
			Handler:    _SocialService_GetMutedUsers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFollowEvents",
			Handler:       _SocialService_StreamFollowEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "social/v1/social.proto",
}
