// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"

	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeInfrastructure creates infrastructure container.
func InitializeInfrastructure(ctx context.Context) (*InfrastructureContainer, error) {
	config := ProvideLoggerConfig()
	logger, err := ProvideLogger(config)
	if err != nil {
		return nil, err
	}
	eventBus := ProvideEventBus(logger)
	server := ProvideGRPCServer(logger)
	infrastructureContainer := &InfrastructureContainer{
		Logger:     logger,
		EventBus:   eventBus,
		GRPCServer: server,
	}
	return infrastructureContainer, nil
}

// wire.go:

// InfrastructureProviderSet provides core infrastructure dependencies.
var InfrastructureProviderSet = wire.NewSet(
	ProvideLoggerConfig,
	ProvideLogger,
	ProvideEventBus,
	ProvideGRPCServer,
)
