// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/0xsj/hexagonal-go/cmd/api/config"
	query6 "github.com/0xsj/hexagonal-go/internal/audit/application/query"
	"github.com/0xsj/hexagonal-go/internal/audit/application/subscriber"
	repository6 "github.com/0xsj/hexagonal-go/internal/audit/infrastructure/repository"
	v1_6 "github.com/0xsj/hexagonal-go/internal/audit/interface/http/v1"
	"github.com/0xsj/hexagonal-go/internal/email"
	command3 "github.com/0xsj/hexagonal-go/internal/email/application/command"
	query3 "github.com/0xsj/hexagonal-go/internal/email/application/query"
	repository3 "github.com/0xsj/hexagonal-go/internal/email/infrastructure/repository"
	v1_3 "github.com/0xsj/hexagonal-go/internal/email/interface/http/v1"
	command4 "github.com/0xsj/hexagonal-go/internal/flags/application/command"
	query4 "github.com/0xsj/hexagonal-go/internal/flags/application/query"
	repository4 "github.com/0xsj/hexagonal-go/internal/flags/infrastructure/repository"
	"github.com/0xsj/hexagonal-go/internal/flags/interface/http/admin"
	v1_4 "github.com/0xsj/hexagonal-go/internal/flags/interface/http/v1"
	"github.com/0xsj/hexagonal-go/internal/identity"
	"github.com/0xsj/hexagonal-go/internal/identity/application/command"
	"github.com/0xsj/hexagonal-go/internal/identity/application/query"
	"github.com/0xsj/hexagonal-go/internal/identity/infrastructure/repository"
	v1 "github.com/0xsj/hexagonal-go/internal/identity/interface/http/v1"
	"github.com/0xsj/hexagonal-go/internal/notifications/application/jobs"
	subscriber2 "github.com/0xsj/hexagonal-go/internal/notifications/application/subscriber"
	command5 "github.com/0xsj/hexagonal-go/internal/permissions/application/command"
	query5 "github.com/0xsj/hexagonal-go/internal/permissions/application/query"
	repository5 "github.com/0xsj/hexagonal-go/internal/permissions/infrastructure/repository"
	v1_5 "github.com/0xsj/hexagonal-go/internal/permissions/interface/http/v1"
	command2 "github.com/0xsj/hexagonal-go/internal/tenant/application/command"
	query2 "github.com/0xsj/hexagonal-go/internal/tenant/application/query"
	repository2 "github.com/0xsj/hexagonal-go/internal/tenant/infrastructure/repository"
	v1_2 "github.com/0xsj/hexagonal-go/internal/tenant/interface/http/v1"
	"github.com/0xsj/hexagonal-go/pkg/cache"
	"github.com/0xsj/hexagonal-go/pkg/database"
	postgres2 "github.com/0xsj/hexagonal-go/pkg/database/postgres"
	email2 "github.com/0xsj/hexagonal-go/pkg/email"
	"github.com/0xsj/hexagonal-go/pkg/http/middleware"
	"github.com/0xsj/hexagonal-go/pkg/observability/logger/console"
	"github.com/0xsj/hexagonal-go/pkg/observability/metrics"
	"github.com/0xsj/hexagonal-go/pkg/observability/tracing"
	"github.com/0xsj/hexagonal-go/pkg/provider"
	"github.com/0xsj/hexagonal-go/pkg/security/jwt"
	"github.com/0xsj/hexagonal-go/pkg/storage"
	"github.com/0xsj/hexagonal-go/pkg/worker/postgres"

	_ "github.com/0xsj/hexagonal-go/docs/swagger"
)

// Injectors from wire.go:

// InitializeApp wires up the entire application.
func InitializeApp(ctx context.Context, cfg *config.AppConfig) (*App, func(), error) {
	options := ProvideLoggerOptions(cfg)
	logger := provider.ProvideLogger(options)
	postgresConfig := ProvidePostgresConfig(cfg)
	db, cleanup, err := provider.ProvideDatabase(postgresConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	publisher := provider.ProvideEventBus(logger)
	postgresUserRepository := repository.NewPostgresUserRepository(db)
	postgresTokenRepository := repository.NewPostgresTokenRepository(db)
	domainEventPublisher := provider.ProvideDomainEventPublisher(publisher, logger)
	registerUserCommand := command.NewRegisterUserCommand(postgresUserRepository, postgresTokenRepository, domainEventPublisher, logger)
	postgresSessionRepository := repository.NewPostgresSessionRepository(db)
	cacheConfig := ProvideCacheConfig(cfg)
	cache, err := provider.ProvideCache(cacheConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sessionRepository := identity.ProvideSessionRepository(postgresSessionRepository, cache)
	jwtConfig := ProvideJWTConfig(cfg)
	service := provider.ProvideJWTService(jwtConfig)
	loginCommand := command.NewLoginCommand(postgresUserRepository, sessionRepository, service, domainEventPublisher, logger)
	logoutCommand := command.NewLogoutCommand(sessionRepository, service, domainEventPublisher, logger)
	refreshTokenCommand := command.NewRefreshTokenCommand(postgresUserRepository, sessionRepository, service, domainEventPublisher, logger)
	verifyEmailCommand := command.NewVerifyEmailCommand(postgresUserRepository, postgresTokenRepository, domainEventPublisher, logger)
	requestPasswordResetCommand := command.NewRequestPasswordResetCommand(postgresUserRepository, postgresTokenRepository, publisher, logger)
	resetPasswordCommand := command.NewResetPasswordCommand(postgresUserRepository, postgresTokenRepository, domainEventPublisher, logger)
	changePasswordCommand := command.NewChangePasswordCommand(postgresUserRepository, domainEventPublisher, logger)
	suspendUserCommand := command.NewSuspendUserCommand(postgresUserRepository, domainEventPublisher, logger)
	reactivateUserCommand := command.NewReactivateUserCommand(postgresUserRepository, domainEventPublisher, logger)
	changeUserRoleCommand := command.NewChangeUserRoleCommand(postgresUserRepository, domainEventPublisher, logger)
	deleteUserCommand := command.NewDeleteUserCommand(postgresUserRepository, domainEventPublisher, logger)
	getUserQuery := query.NewGetUserQuery(postgresUserRepository)
	getCurrentUserQuery := query.NewGetCurrentUserQuery(postgresUserRepository)
	listUsersQuery := query.NewListUsersQuery(postgresUserRepository)
	listSessionsQuery := query.NewListSessionsQuery(sessionRepository)
	postgresOAuthRepository := repository.NewPostgresOAuthRepository(db)
	v := identity.ProvideOAuthProviders(logger)
	oAuthLoginCommand := command.NewOAuthLoginCommand(postgresUserRepository, postgresOAuthRepository, sessionRepository, v, service, domainEventPublisher, logger)
	stateManager := identity.ProvideStateManager()
	oAuthHandler := v1.NewOAuthHandler(oAuthLoginCommand, stateManager, v, logger)
	handler := v1.NewHandler(registerUserCommand, loginCommand, logoutCommand, refreshTokenCommand, verifyEmailCommand, requestPasswordResetCommand, resetPasswordCommand, changePasswordCommand, suspendUserCommand, reactivateUserCommand, changeUserRoleCommand, deleteUserCommand, getUserQuery, getCurrentUserQuery, listUsersQuery, listSessionsQuery, oAuthHandler, logger)
	postgresRepository := repository2.NewPostgresRepository(db)
	createTenantCommand := command2.NewCreateTenantCommand(postgresRepository, domainEventPublisher, logger)
	updateTenantCommand := command2.NewUpdateTenantCommand(postgresRepository, domainEventPublisher, logger)
	updateSettingsCommand := command2.NewUpdateSettingsCommand(postgresRepository, domainEventPublisher, logger)
	suspendTenantCommand := command2.NewSuspendTenantCommand(postgresRepository, domainEventPublisher, logger)
	reactivateTenantCommand := command2.NewReactivateTenantCommand(postgresRepository, domainEventPublisher, logger)
	changePlanCommand := command2.NewChangePlanCommand(postgresRepository, domainEventPublisher, logger)
	deleteTenantCommand := command2.NewDeleteTenantCommand(postgresRepository, domainEventPublisher, logger)
	getTenantQuery := query2.NewGetTenantQuery(postgresRepository)
	getTenantBySlugQuery := query2.NewGetTenantBySlugQuery(postgresRepository)
	listTenantsQuery := query2.NewListTenantsQuery(postgresRepository)
	v1Handler := v1_2.NewHandler(createTenantCommand, updateTenantCommand, updateSettingsCommand, suspendTenantCommand, reactivateTenantCommand, changePlanCommand, deleteTenantCommand, getTenantQuery, getTenantBySlugQuery, listTenantsQuery, logger)
	repositoryPostgresRepository := repository3.NewPostgresRepository(db)
	createTemplateCommand := command3.NewCreateTemplateCommand(repositoryPostgresRepository, domainEventPublisher, logger)
	updateTemplateCommand := command3.NewUpdateTemplateCommand(repositoryPostgresRepository, domainEventPublisher, logger)
	activateTemplateCommand := command3.NewActivateTemplateCommand(repositoryPostgresRepository, domainEventPublisher, logger)
	archiveTemplateCommand := command3.NewArchiveTemplateCommand(repositoryPostgresRepository, domainEventPublisher, logger)
	deleteTemplateCommand := command3.NewDeleteTemplateCommand(repositoryPostgresRepository, domainEventPublisher, logger)
	getTemplateQuery := query3.NewGetTemplateQuery(repositoryPostgresRepository)
	listTemplatesQuery := query3.NewListTemplatesQuery(repositoryPostgresRepository)
	renderer := email.ProvideRenderer()
	previewTemplateQuery := query3.NewPreviewTemplateQuery(repositoryPostgresRepository, renderer)
	handler2 := v1_3.NewHandler(createTemplateCommand, updateTemplateCommand, activateTemplateCommand, archiveTemplateCommand, deleteTemplateCommand, getTemplateQuery, listTemplatesQuery, previewTemplateQuery, logger)
	postgresRepository2 := repository4.NewPostgresRepository(db)
	createFlagCommand := command4.NewCreateFlagCommand(postgresRepository2, domainEventPublisher, logger)
	updateFlagCommand := command4.NewUpdateFlagCommand(postgresRepository2, domainEventPublisher, logger)
	deleteFlagCommand := command4.NewDeleteFlagCommand(postgresRepository2, domainEventPublisher, logger)
	enableFlagCommand := command4.NewEnableFlagCommand(postgresRepository2, domainEventPublisher, logger)
	disableFlagCommand := command4.NewDisableFlagCommand(postgresRepository2, domainEventPublisher, logger)
	addRuleCommand := command4.NewAddRuleCommand(postgresRepository2, domainEventPublisher, logger)
	removeRuleCommand := command4.NewRemoveRuleCommand(postgresRepository2, domainEventPublisher, logger)
	setOverrideCommand := command4.NewSetOverrideCommand(postgresRepository2, domainEventPublisher, logger)
	removeOverrideCommand := command4.NewRemoveOverrideCommand(postgresRepository2, domainEventPublisher, logger)
	getFlagQuery := query4.NewGetFlagQuery(postgresRepository2)
	listFlagsQuery := query4.NewListFlagsQuery(postgresRepository2)
	evaluateFlagQuery := query4.NewEvaluateFlagQuery(postgresRepository2)
	handler3 := v1_4.NewHandler(createFlagCommand, updateFlagCommand, deleteFlagCommand, enableFlagCommand, disableFlagCommand, addRuleCommand, removeRuleCommand, setOverrideCommand, removeOverrideCommand, getFlagQuery, listFlagsQuery, evaluateFlagQuery, logger)
	adminHandler := admin.NewHandler(createFlagCommand, updateFlagCommand, deleteFlagCommand, enableFlagCommand, disableFlagCommand, getFlagQuery, listFlagsQuery, logger)
	postgresRoleRepository := repository5.NewPostgresRoleRepository(db)
	createRoleCommand := command5.NewCreateRoleCommand(postgresRoleRepository, domainEventPublisher, logger)
	updateRoleCommand := command5.NewUpdateRoleCommand(postgresRoleRepository, domainEventPublisher, logger)
	postgresAssignmentRepository := repository5.NewPostgresAssignmentRepository(db)
	deleteRoleCommand := command5.NewDeleteRoleCommand(postgresRoleRepository, postgresAssignmentRepository, domainEventPublisher, logger)
	assignRoleCommand := command5.NewAssignRoleCommand(postgresRoleRepository, postgresAssignmentRepository, domainEventPublisher, logger)
	revokeRoleCommand := command5.NewRevokeRoleCommand(postgresRoleRepository, postgresAssignmentRepository, domainEventPublisher, logger)
	getRoleQuery := query5.NewGetRoleQuery(postgresRoleRepository, logger)
	listRolesQuery := query5.NewListRolesQuery(postgresRoleRepository, logger)
	getUserPermissionsQuery := query5.NewGetUserPermissionsQuery(postgresRoleRepository, postgresAssignmentRepository, logger)
	checkPermissionQuery := query5.NewCheckPermissionQuery(postgresRoleRepository, postgresAssignmentRepository, logger)
	handler4 := v1_5.NewHandler(createRoleCommand, updateRoleCommand, deleteRoleCommand, assignRoleCommand, revokeRoleCommand, getRoleQuery, listRolesQuery, getUserPermissionsQuery, checkPermissionQuery, logger)
	postgresRepository3 := repository6.NewPostgresRepository(db)
	getEntryQuery := query6.NewGetEntryQuery(postgresRepository3, logger)
	listEntriesQuery := query6.NewListEntriesQuery(postgresRepository3, logger)
	getResourceTrailQuery := query6.NewGetResourceTrailQuery(postgresRepository3, logger)
	getActorActivityQuery := query6.NewGetActorActivityQuery(postgresRepository3, logger)
	handler5 := v1_6.NewHandler(getEntryQuery, listEntriesQuery, getResourceTrailQuery, getActorActivityQuery, logger)
	client := provider.ProvideFlagsClient(db, logger)
	eventSubscriber := subscriber.NewEventSubscriber(postgresRepository3, logger)
	queue := ProvideJobQueue(db)
	templateRepositoryAdapter := repository3.NewTemplateRepositoryAdapter(repositoryPostgresRepository)
	templateService := email2.NewTemplateService(templateRepositoryAdapter, renderer)
	userEventSubscriber := subscriber2.NewUserEventSubscriber(queue, templateService, logger)
	tenantEventSubscriber := subscriber2.NewTenantEventSubscriber(queue, templateService, logger)
	emailConfig := ProvideEmailConfig(cfg)
	sender := provider.ProvideEmailSender(emailConfig)
	sendEmailHandler := jobs.NewSendEmailHandler(sender, logger)
	storageConfig := ProvideStorageConfig(cfg)
	storage, err := provider.ProvideStorage(ctx, storageConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metricsConfig := ProvideMetricsConfig(cfg)
	metricsProvider := provider.ProvideMetricsProvider(metricsConfig)
	tracingConfig := ProvideTracingConfig(cfg)
	tracingProvider, err := provider.ProvideTracingProvider(ctx, tracingConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpMetrics := middleware.NewHTTPMetrics(metricsProvider)
	app := &App{
		Logger:                       logger,
		DB:                           db,
		EventBus:                     publisher,
		IdentityHandler:              handler,
		TenantHandler:                v1Handler,
		EmailHandler:                 handler2,
		FlagsHandler:                 handler3,
		FlagsAdminHandler:            adminHandler,
		PermissionsHandler:           handler4,
		AuditHandler:                 handler5,
		FlagsClient:                  client,
		AuditSubscriber:              eventSubscriber,
		UserNotificationSubscriber:   userEventSubscriber,
		TenantNotificationSubscriber: tenantEventSubscriber,
		JobQueue:                     queue,
		SendEmailJobHandler:          sendEmailHandler,
		JWTService:                   service,
		Cache:                        cache,
		PermissionChecker:            checkPermissionQuery,
		Storage:                      storage,
		MetricsProvider:              metricsProvider,
		TracingProvider:              tracingProvider,
		HTTPMetrics:                  httpMetrics,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// ProvideJobQueue creates a PostgreSQL-backed job queue.
func ProvideJobQueue(db database.DB) *postgres.Queue {
	return postgres.NewQueue(db)
}

// ProvidePostgresConfig extracts database config from AppConfig.
func ProvidePostgresConfig(cfg *config.AppConfig) postgres2.Config {
	return cfg.Database
}

// ProvideLoggerOptions extracts logger options from AppConfig.
func ProvideLoggerOptions(cfg *config.AppConfig) console.Options {
	return cfg.Logger
}

// ProvideEmailConfig extracts email config from AppConfig.
func ProvideEmailConfig(cfg *config.AppConfig) email2.Config {
	return cfg.Email
}

// ProvideMetricsConfig extracts metrics config from AppConfig.
func ProvideMetricsConfig(cfg *config.AppConfig) metrics.Config {
	return cfg.Metrics
}

// ProvideTracingConfig extracts tracing config from AppConfig.
func ProvideTracingConfig(cfg *config.AppConfig) tracing.Config {
	return cfg.Tracing
}

// ProvideJWTConfig extracts JWT config from AppConfig.
func ProvideJWTConfig(cfg *config.AppConfig) jwt.Config {
	return cfg.JWT
}

// ProvideCacheConfig extracts cache config from AppConfig.
func ProvideCacheConfig(cfg *config.AppConfig) cache.Config {
	return cfg.Cache
}

// ProvideStorageConfig extracts storage config from AppConfig.
func ProvideStorageConfig(cfg *config.AppConfig) storage.Config {
	return cfg.Storage
}
