// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: notifications/v1/notifications.proto

package notificationsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "github.com/0xsj/nexus/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification type
type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_FOLLOW      NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_LIKE        NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_COMMENT     NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_MENTION     NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_MESSAGE     NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_SYSTEM      NotificationType = 6
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_FOLLOW",
		2: "NOTIFICATION_TYPE_LIKE",
		3: "NOTIFICATION_TYPE_COMMENT",
		4: "NOTIFICATION_TYPE_MENTION",
		5: "NOTIFICATION_TYPE_MESSAGE",
		6: "NOTIFICATION_TYPE_SYSTEM",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"NOTIFICATION_TYPE_FOLLOW":      1,
		"NOTIFICATION_TYPE_LIKE":        2,
		"NOTIFICATION_TYPE_COMMENT":     3,
		"NOTIFICATION_TYPE_MENTION":     4,
		"NOTIFICATION_TYPE_MESSAGE":     5,
		"NOTIFICATION_TYPE_SYSTEM":      6,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_v1_notifications_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notifications_v1_notifications_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

// Push notification platform
type PushPlatform int32

const (
	PushPlatform_PUSH_PLATFORM_UNSPECIFIED PushPlatform = 0
	PushPlatform_PUSH_PLATFORM_FCM         PushPlatform = 1 // Firebase Cloud Messaging (Android)
	PushPlatform_PUSH_PLATFORM_APNS        PushPlatform = 2 // Apple Push Notification Service (iOS)
	PushPlatform_PUSH_PLATFORM_WEB         PushPlatform = 3 // Web Push
)

// Enum value maps for PushPlatform.
var (
	PushPlatform_name = map[int32]string{
		0: "PUSH_PLATFORM_UNSPECIFIED",
		1: "PUSH_PLATFORM_FCM",
		2: "PUSH_PLATFORM_APNS",
		3: "PUSH_PLATFORM_WEB",
	}
	PushPlatform_value = map[string]int32{
		"PUSH_PLATFORM_UNSPECIFIED": 0,
		"PUSH_PLATFORM_FCM":         1,
		"PUSH_PLATFORM_APNS":        2,
		"PUSH_PLATFORM_WEB":         3,
	}
)

func (x PushPlatform) Enum() *PushPlatform {
	p := new(PushPlatform)
	*p = x
	return p
}

func (x PushPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_v1_notifications_proto_enumTypes[1].Descriptor()
}

func (PushPlatform) Type() protoreflect.EnumType {
	return &file_notifications_v1_notifications_proto_enumTypes[1]
}

func (x PushPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushPlatform.Descriptor instead.
func (PushPlatform) EnumDescriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

// Notification resource
type Notification struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type      NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=notifications.v1.NotificationType" json:"type,omitempty"`
	Title     string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body      string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Data      map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional data (e.g., user_id, post_id)
	IsRead    bool                   `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReadAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	// Optional: Actor who triggered the notification
	Actor *Actor `protobuf:"bytes,10,opt,name=actor,proto3,oneof" json:"actor,omitempty"`
	// Optional: Target resource (post, comment, etc.)
	TargetType    *string `protobuf:"bytes,11,opt,name=target_type,json=targetType,proto3,oneof" json:"target_type,omitempty"`
	TargetId      *string `protobuf:"bytes,12,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *Notification) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *Notification) GetTargetType() string {
	if x != nil && x.TargetType != nil {
		return *x.TargetType
	}
	return ""
}

func (x *Notification) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

// Actor who triggered the notification
type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Actor) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Actor) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// Device registration
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Platform      PushPlatform           `protobuf:"varint,2,opt,name=platform,proto3,enum=notifications.v1.PushPlatform" json:"platform,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *Device) GetPlatform() PushPlatform {
	if x != nil {
		return x.Platform
	}
	return PushPlatform_PUSH_PLATFORM_UNSPECIFIED
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Device) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Device) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

// Notification preferences
type NotificationPreferences struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PushEnabled  bool                   `protobuf:"varint,1,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	EmailEnabled bool                   `protobuf:"varint,2,opt,name=email_enabled,json=emailEnabled,proto3" json:"email_enabled,omitempty"`
	InAppEnabled bool                   `protobuf:"varint,3,opt,name=in_app_enabled,json=inAppEnabled,proto3" json:"in_app_enabled,omitempty"`
	// Per-type preferences
	TypePreferences map[string]bool `protobuf:"bytes,4,rep,name=type_preferences,json=typePreferences,proto3" json:"type_preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // e.g., "follow": true, "like": false
	// Quiet hours
	QuietHours    *QuietHours `protobuf:"bytes,5,opt,name=quiet_hours,json=quietHours,proto3,oneof" json:"quiet_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationPreferences) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

func (x *NotificationPreferences) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *NotificationPreferences) GetInAppEnabled() bool {
	if x != nil {
		return x.InAppEnabled
	}
	return false
}

func (x *NotificationPreferences) GetTypePreferences() map[string]bool {
	if x != nil {
		return x.TypePreferences
	}
	return nil
}

func (x *NotificationPreferences) GetQuietHours() *QuietHours {
	if x != nil {
		return x.QuietHours
	}
	return nil
}

// Quiet hours (do not disturb)
type QuietHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // e.g., "22:00"
	EndTime       string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // e.g., "08:00"
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`                    // IANA timezone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuietHours) Reset() {
	*x = QuietHours{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuietHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuietHours) ProtoMessage() {}

func (x *QuietHours) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuietHours.ProtoReflect.Descriptor instead.
func (*QuietHours) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *QuietHours) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *QuietHours) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QuietHours) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *QuietHours) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// Notification event (for streaming)
type NotificationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Notification  *Notification          `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NotificationEvent) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *NotificationEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// RegisterDevice
type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Platform      PushPlatform           `protobuf:"varint,2,opt,name=platform,proto3,enum=notifications.v1.PushPlatform" json:"platform,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterDeviceRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *RegisterDeviceRequest) GetPlatform() PushPlatform {
	if x != nil {
		return x.Platform
	}
	return PushPlatform_PUSH_PLATFORM_UNSPECIFIED
}

func (x *RegisterDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *RegisterDeviceResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UnregisterDevice
type UnregisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceRequest) Reset() {
	*x = UnregisterDeviceRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceRequest) ProtoMessage() {}

func (x *UnregisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{8}
}

func (x *UnregisterDeviceRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

type UnregisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceResponse) Reset() {
	*x = UnregisterDeviceResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceResponse) ProtoMessage() {}

func (x *UnregisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{9}
}

func (x *UnregisterDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterDeviceResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetNotification
type GetNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{10}
}

func (x *GetNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type GetNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{11}
}

func (x *GetNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *GetNotificationResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ListNotifications
type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	UnreadOnly    *bool                  `protobuf:"varint,2,opt,name=unread_only,json=unreadOnly,proto3,oneof" json:"unread_only,omitempty"`
	Type          *NotificationType      `protobuf:"varint,3,opt,name=type,proto3,enum=notifications.v1.NotificationType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{12}
}

func (x *ListNotificationsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil && x.UnreadOnly != nil {
		return *x.UnreadOnly
	}
	return false
}

func (x *ListNotificationsRequest) GetType() NotificationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{13}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotificationsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ListNotificationsResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MarkAsRead
type MarkAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{14}
}

func (x *MarkAsReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{15}
}

func (x *MarkAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkAsReadResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MarkAllAsRead
type MarkAllAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadRequest) Reset() {
	*x = MarkAllAsReadRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadRequest) ProtoMessage() {}

func (x *MarkAllAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{16}
}

type MarkAllAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MarkedCount   int32                  `protobuf:"varint,2,opt,name=marked_count,json=markedCount,proto3" json:"marked_count,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadResponse) Reset() {
	*x = MarkAllAsReadResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadResponse) ProtoMessage() {}

func (x *MarkAllAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{17}
}

func (x *MarkAllAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkAllAsReadResponse) GetMarkedCount() int32 {
	if x != nil {
		return x.MarkedCount
	}
	return 0
}

func (x *MarkAllAsReadResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DeleteNotification
type DeleteNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type DeleteNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationResponse) Reset() {
	*x = DeleteNotificationResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationResponse) ProtoMessage() {}

func (x *DeleteNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteNotificationResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetPreferences
type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{20}
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	Metadata      *v1.ResponseMetadata     `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{21}
}

func (x *GetPreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *GetPreferencesResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpdatePreferences
type UpdatePreferencesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PushEnabled     *bool                  `protobuf:"varint,1,opt,name=push_enabled,json=pushEnabled,proto3,oneof" json:"push_enabled,omitempty"`
	EmailEnabled    *bool                  `protobuf:"varint,2,opt,name=email_enabled,json=emailEnabled,proto3,oneof" json:"email_enabled,omitempty"`
	InAppEnabled    *bool                  `protobuf:"varint,3,opt,name=in_app_enabled,json=inAppEnabled,proto3,oneof" json:"in_app_enabled,omitempty"`
	TypePreferences map[string]bool        `protobuf:"bytes,4,rep,name=type_preferences,json=typePreferences,proto3" json:"type_preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	QuietHours      *QuietHours            `protobuf:"bytes,5,opt,name=quiet_hours,json=quietHours,proto3,oneof" json:"quiet_hours,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{22}
}

func (x *UpdatePreferencesRequest) GetPushEnabled() bool {
	if x != nil && x.PushEnabled != nil {
		return *x.PushEnabled
	}
	return false
}

func (x *UpdatePreferencesRequest) GetEmailEnabled() bool {
	if x != nil && x.EmailEnabled != nil {
		return *x.EmailEnabled
	}
	return false
}

func (x *UpdatePreferencesRequest) GetInAppEnabled() bool {
	if x != nil && x.InAppEnabled != nil {
		return *x.InAppEnabled
	}
	return false
}

func (x *UpdatePreferencesRequest) GetTypePreferences() map[string]bool {
	if x != nil {
		return x.TypePreferences
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetQuietHours() *QuietHours {
	if x != nil {
		return x.QuietHours
	}
	return nil
}

type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	Metadata      *v1.ResponseMetadata     `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{23}
}

func (x *UpdatePreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UpdatePreferencesResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StreamNotifications (server streaming)
type StreamNotificationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User identified from auth token
	// Optional: filter by types
	Types         []NotificationType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=notifications.v1.NotificationType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNotificationsRequest) Reset() {
	*x = StreamNotificationsRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationsRequest) ProtoMessage() {}

func (x *StreamNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNotificationsRequest.ProtoReflect.Descriptor instead.
func (*StreamNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{24}
}

func (x *StreamNotificationsRequest) GetTypes() []NotificationType {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_notifications_v1_notifications_proto protoreflect.FileDescriptor

const file_notifications_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"$notifications/v1/notifications.proto\x12\x10notifications.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\xbd\x04\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x126\n" +
	"\x04type\x18\x03 \x01(\x0e2\".notifications.v1.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12<\n" +
	"\x04data\x18\x06 \x03(\v2(.notifications.v1.Notification.DataEntryR\x04data\x12\x17\n" +
	"\ais_read\x18\a \x01(\bR\x06isRead\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\aread_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\x122\n" +
	"\x05actor\x18\n" +
	" \x01(\v2\x17.notifications.v1.ActorH\x00R\x05actor\x88\x01\x01\x12$\n" +
	"\vtarget_type\x18\v \x01(\tH\x01R\n" +
	"targetType\x88\x01\x01\x12 \n" +
	"\ttarget_id\x18\f \x01(\tH\x02R\btargetId\x88\x01\x01\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_actorB\x0e\n" +
	"\f_target_typeB\f\n" +
	"\n" +
	"_target_id\"[\n" +
	"\x05Actor\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"\xa4\x02\n" +
	"\x06Device\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12:\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x1e.notifications.v1.PushPlatformR\bplatform\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\x8a\x03\n" +
	"\x17NotificationPreferences\x12!\n" +
	"\fpush_enabled\x18\x01 \x01(\bR\vpushEnabled\x12#\n" +
	"\remail_enabled\x18\x02 \x01(\bR\femailEnabled\x12$\n" +
	"\x0ein_app_enabled\x18\x03 \x01(\bR\finAppEnabled\x12i\n" +
	"\x10type_preferences\x18\x04 \x03(\v2>.notifications.v1.NotificationPreferences.TypePreferencesEntryR\x0ftypePreferences\x12B\n" +
	"\vquiet_hours\x18\x05 \x01(\v2\x1c.notifications.v1.QuietHoursH\x00R\n" +
	"quietHours\x88\x01\x01\x1aB\n" +
	"\x14TypePreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\x0e\n" +
	"\f_quiet_hours\"|\n" +
	"\n" +
	"QuietHours\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\"\xac\x01\n" +
	"\x11NotificationEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12B\n" +
	"\fnotification\x18\x02 \x01(\v2\x1e.notifications.v1.NotificationR\fnotification\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb4\x01\n" +
	"\x15RegisterDeviceRequest\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12:\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x1e.notifications.v1.PushPlatformR\bplatform\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\"\x83\x01\n" +
	"\x16RegisterDeviceResponse\x120\n" +
	"\x06device\x18\x01 \x01(\v2\x18.notifications.v1.DeviceR\x06device\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"<\n" +
	"\x17UnregisterDeviceRequest\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\"m\n" +
	"\x18UnregisterDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"A\n" +
	"\x16GetNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"\x96\x01\n" +
	"\x17GetNotificationResponse\x12B\n" +
	"\fnotification\x18\x01 \x01(\v2\x1e.notifications.v1.NotificationR\fnotification\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\xd4\x01\n" +
	"\x18ListNotificationsRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12$\n" +
	"\vunread_only\x18\x02 \x01(\bH\x00R\n" +
	"unreadOnly\x88\x01\x01\x12;\n" +
	"\x04type\x18\x03 \x01(\x0e2\".notifications.v1.NotificationTypeH\x01R\x04type\x88\x01\x01B\x0e\n" +
	"\f_unread_onlyB\a\n" +
	"\x05_type\"\xfc\x01\n" +
	"\x19ListNotificationsResponse\x12D\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1e.notifications.v1.NotificationR\rnotifications\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\x12!\n" +
	"\funread_count\x18\x03 \x01(\x05R\vunreadCount\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"<\n" +
	"\x11MarkAsReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"g\n" +
	"\x12MarkAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x16\n" +
	"\x14MarkAllAsReadRequest\"\x8d\x01\n" +
	"\x15MarkAllAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fmarked_count\x18\x02 \x01(\x05R\vmarkedCount\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"D\n" +
	"\x19DeleteNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"o\n" +
	"\x1aDeleteNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x17\n" +
	"\x15GetPreferencesRequest\"\x9e\x01\n" +
	"\x16GetPreferencesResponse\x12K\n" +
	"\vpreferences\x18\x01 \x01(\v2).notifications.v1.NotificationPreferencesR\vpreferences\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\xd1\x03\n" +
	"\x18UpdatePreferencesRequest\x12&\n" +
	"\fpush_enabled\x18\x01 \x01(\bH\x00R\vpushEnabled\x88\x01\x01\x12(\n" +
	"\remail_enabled\x18\x02 \x01(\bH\x01R\femailEnabled\x88\x01\x01\x12)\n" +
	"\x0ein_app_enabled\x18\x03 \x01(\bH\x02R\finAppEnabled\x88\x01\x01\x12j\n" +
	"\x10type_preferences\x18\x04 \x03(\v2?.notifications.v1.UpdatePreferencesRequest.TypePreferencesEntryR\x0ftypePreferences\x12B\n" +
	"\vquiet_hours\x18\x05 \x01(\v2\x1c.notifications.v1.QuietHoursH\x03R\n" +
	"quietHours\x88\x01\x01\x1aB\n" +
	"\x14TypePreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\x0f\n" +
	"\r_push_enabledB\x10\n" +
	"\x0e_email_enabledB\x11\n" +
	"\x0f_in_app_enabledB\x0e\n" +
	"\f_quiet_hours\"\xa1\x01\n" +
	"\x19UpdatePreferencesResponse\x12K\n" +
	"\vpreferences\x18\x01 \x01(\v2).notifications.v1.NotificationPreferencesR\vpreferences\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"V\n" +
	"\x1aStreamNotificationsRequest\x128\n" +
	"\x05types\x18\x01 \x03(\x0e2\".notifications.v1.NotificationTypeR\x05types*\xea\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18NOTIFICATION_TYPE_FOLLOW\x10\x01\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_LIKE\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_COMMENT\x10\x03\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_MENTION\x10\x04\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_MESSAGE\x10\x05\x12\x1c\n" +
	"\x18NOTIFICATION_TYPE_SYSTEM\x10\x06*s\n" +
	"\fPushPlatform\x12\x1d\n" +
	"\x19PUSH_PLATFORM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PUSH_PLATFORM_FCM\x10\x01\x12\x16\n" +
	"\x12PUSH_PLATFORM_APNS\x10\x02\x12\x15\n" +
	"\x11PUSH_PLATFORM_WEB\x10\x032\xcc\v\n" +
	"\x13NotificationService\x12\x89\x01\n" +
	"\x0eRegisterDevice\x12'.notifications.v1.RegisterDeviceRequest\x1a(.notifications.v1.RegisterDeviceResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/notifications/devices\x12\x9b\x01\n" +
	"\x10UnregisterDevice\x12).notifications.v1.UnregisterDeviceRequest\x1a*.notifications.v1.UnregisterDeviceResponse\"0\x82\xd3\xe4\x93\x02**(/v1/notifications/devices/{device_token}\x12\x93\x01\n" +
	"\x0fGetNotification\x12(.notifications.v1.GetNotificationRequest\x1a).notifications.v1.GetNotificationResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/notifications/{notification_id}\x12\x87\x01\n" +
	"\x11ListNotifications\x12*.notifications.v1.ListNotificationsRequest\x1a+.notifications.v1.ListNotificationsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/notifications\x12\x8c\x01\n" +
	"\n" +
	"MarkAsRead\x12#.notifications.v1.MarkAsReadRequest\x1a$.notifications.v1.MarkAsReadResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/notifications/{notification_id}/read\x12\x87\x01\n" +
	"\rMarkAllAsRead\x12&.notifications.v1.MarkAllAsReadRequest\x1a'.notifications.v1.MarkAllAsReadResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/notifications/read-all\x12\x9c\x01\n" +
	"\x12DeleteNotification\x12+.notifications.v1.DeleteNotificationRequest\x1a,.notifications.v1.DeleteNotificationResponse\"+\x82\xd3\xe4\x93\x02%*#/v1/notifications/{notification_id}\x12\x8a\x01\n" +
	"\x0eGetPreferences\x12'.notifications.v1.GetPreferencesRequest\x1a(.notifications.v1.GetPreferencesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/notifications/preferences\x12\x96\x01\n" +
	"\x11UpdatePreferences\x12*.notifications.v1.UpdatePreferencesRequest\x1a+.notifications.v1.UpdatePreferencesResponse\"(\x82\xd3\xe4\x93\x02\":\x01*2\x1d/v1/notifications/preferences\x12\x8c\x01\n" +
	"\x13StreamNotifications\x12,.notifications.v1.StreamNotificationsRequest\x1a#.notifications.v1.NotificationEvent\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/notifications/stream0\x01B\xc7\x01\n" +
	"\x14com.notifications.v1B\x12NotificationsProtoP\x01Z:github.com/0xsj/nexus/api/notifications/v1;notificationsv1\xa2\x02\x03NXX\xaa\x02\x10Notifications.V1\xca\x02\x10Notifications\\V1\xe2\x02\x1cNotifications\\V1\\GPBMetadata\xea\x02\x11Notifications::V1b\x06proto3"

var (
	file_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_notifications_v1_notifications_proto_rawDescData []byte
)

func file_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_v1_notifications_proto_rawDesc), len(file_notifications_v1_notifications_proto_rawDesc)))
	})
	return file_notifications_v1_notifications_proto_rawDescData
}

var file_notifications_v1_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_notifications_v1_notifications_proto_goTypes = []any{
	(NotificationType)(0),              // 0: notifications.v1.NotificationType
	(PushPlatform)(0),                  // 1: notifications.v1.PushPlatform
	(*Notification)(nil),               // 2: notifications.v1.Notification
	(*Actor)(nil),                      // 3: notifications.v1.Actor
	(*Device)(nil),                     // 4: notifications.v1.Device
	(*NotificationPreferences)(nil),    // 5: notifications.v1.NotificationPreferences
	(*QuietHours)(nil),                 // 6: notifications.v1.QuietHours
	(*NotificationEvent)(nil),          // 7: notifications.v1.NotificationEvent
	(*RegisterDeviceRequest)(nil),      // 8: notifications.v1.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),     // 9: notifications.v1.RegisterDeviceResponse
	(*UnregisterDeviceRequest)(nil),    // 10: notifications.v1.UnregisterDeviceRequest
	(*UnregisterDeviceResponse)(nil),   // 11: notifications.v1.UnregisterDeviceResponse
	(*GetNotificationRequest)(nil),     // 12: notifications.v1.GetNotificationRequest
	(*GetNotificationResponse)(nil),    // 13: notifications.v1.GetNotificationResponse
	(*ListNotificationsRequest)(nil),   // 14: notifications.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),  // 15: notifications.v1.ListNotificationsResponse
	(*MarkAsReadRequest)(nil),          // 16: notifications.v1.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),         // 17: notifications.v1.MarkAsReadResponse
	(*MarkAllAsReadRequest)(nil),       // 18: notifications.v1.MarkAllAsReadRequest
	(*MarkAllAsReadResponse)(nil),      // 19: notifications.v1.MarkAllAsReadResponse
	(*DeleteNotificationRequest)(nil),  // 20: notifications.v1.DeleteNotificationRequest
	(*DeleteNotificationResponse)(nil), // 21: notifications.v1.DeleteNotificationResponse
	(*GetPreferencesRequest)(nil),      // 22: notifications.v1.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),     // 23: notifications.v1.GetPreferencesResponse
	(*UpdatePreferencesRequest)(nil),   // 24: notifications.v1.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil),  // 25: notifications.v1.UpdatePreferencesResponse
	(*StreamNotificationsRequest)(nil), // 26: notifications.v1.StreamNotificationsRequest
	nil,                                // 27: notifications.v1.Notification.DataEntry
	nil,                                // 28: notifications.v1.NotificationPreferences.TypePreferencesEntry
	nil,                                // 29: notifications.v1.UpdatePreferencesRequest.TypePreferencesEntry
	(*timestamppb.Timestamp)(nil),      // 30: google.protobuf.Timestamp
	(*v1.ResponseMetadata)(nil),        // 31: common.v1.ResponseMetadata
	(*v1.PaginationRequest)(nil),       // 32: common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),      // 33: common.v1.PaginationResponse
}
var file_notifications_v1_notifications_proto_depIdxs = []int32{
	0,  // 0: notifications.v1.Notification.type:type_name -> notifications.v1.NotificationType
	27, // 1: notifications.v1.Notification.data:type_name -> notifications.v1.Notification.DataEntry
	30, // 2: notifications.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	30, // 3: notifications.v1.Notification.read_at:type_name -> google.protobuf.Timestamp
	3,  // 4: notifications.v1.Notification.actor:type_name -> notifications.v1.Actor
	1,  // 5: notifications.v1.Device.platform:type_name -> notifications.v1.PushPlatform
	30, // 6: notifications.v1.Device.registered_at:type_name -> google.protobuf.Timestamp
	30, // 7: notifications.v1.Device.last_used_at:type_name -> google.protobuf.Timestamp
	28, // 8: notifications.v1.NotificationPreferences.type_preferences:type_name -> notifications.v1.NotificationPreferences.TypePreferencesEntry
	6,  // 9: notifications.v1.NotificationPreferences.quiet_hours:type_name -> notifications.v1.QuietHours
	2,  // 10: notifications.v1.NotificationEvent.notification:type_name -> notifications.v1.Notification
	30, // 11: notifications.v1.NotificationEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 12: notifications.v1.RegisterDeviceRequest.platform:type_name -> notifications.v1.PushPlatform
	4,  // 13: notifications.v1.RegisterDeviceResponse.device:type_name -> notifications.v1.Device
	31, // 14: notifications.v1.RegisterDeviceResponse.metadata:type_name -> common.v1.ResponseMetadata
	31, // 15: notifications.v1.UnregisterDeviceResponse.metadata:type_name -> common.v1.ResponseMetadata
	2,  // 16: notifications.v1.GetNotificationResponse.notification:type_name -> notifications.v1.Notification
	31, // 17: notifications.v1.GetNotificationResponse.metadata:type_name -> common.v1.ResponseMetadata
	32, // 18: notifications.v1.ListNotificationsRequest.pagination:type_name -> common.v1.PaginationRequest
	0,  // 19: notifications.v1.ListNotificationsRequest.type:type_name -> notifications.v1.NotificationType
	2,  // 20: notifications.v1.ListNotificationsResponse.notifications:type_name -> notifications.v1.Notification
	33, // 21: notifications.v1.ListNotificationsResponse.pagination:type_name -> common.v1.PaginationResponse
	31, // 22: notifications.v1.ListNotificationsResponse.metadata:type_name -> common.v1.ResponseMetadata
	31, // 23: notifications.v1.MarkAsReadResponse.metadata:type_name -> common.v1.ResponseMetadata
	31, // 24: notifications.v1.MarkAllAsReadResponse.metadata:type_name -> common.v1.ResponseMetadata
	31, // 25: notifications.v1.DeleteNotificationResponse.metadata:type_name -> common.v1.ResponseMetadata
	5,  // 26: notifications.v1.GetPreferencesResponse.preferences:type_name -> notifications.v1.NotificationPreferences
	31, // 27: notifications.v1.GetPreferencesResponse.metadata:type_name -> common.v1.ResponseMetadata
	29, // 28: notifications.v1.UpdatePreferencesRequest.type_preferences:type_name -> notifications.v1.UpdatePreferencesRequest.TypePreferencesEntry
	6,  // 29: notifications.v1.UpdatePreferencesRequest.quiet_hours:type_name -> notifications.v1.QuietHours
	5,  // 30: notifications.v1.UpdatePreferencesResponse.preferences:type_name -> notifications.v1.NotificationPreferences
	31, // 31: notifications.v1.UpdatePreferencesResponse.metadata:type_name -> common.v1.ResponseMetadata
	0,  // 32: notifications.v1.StreamNotificationsRequest.types:type_name -> notifications.v1.NotificationType
	8,  // 33: notifications.v1.NotificationService.RegisterDevice:input_type -> notifications.v1.RegisterDeviceRequest
	10, // 34: notifications.v1.NotificationService.UnregisterDevice:input_type -> notifications.v1.UnregisterDeviceRequest
	12, // 35: notifications.v1.NotificationService.GetNotification:input_type -> notifications.v1.GetNotificationRequest
	14, // 36: notifications.v1.NotificationService.ListNotifications:input_type -> notifications.v1.ListNotificationsRequest
	16, // 37: notifications.v1.NotificationService.MarkAsRead:input_type -> notifications.v1.MarkAsReadRequest
	18, // 38: notifications.v1.NotificationService.MarkAllAsRead:input_type -> notifications.v1.MarkAllAsReadRequest
	20, // 39: notifications.v1.NotificationService.DeleteNotification:input_type -> notifications.v1.DeleteNotificationRequest
	22, // 40: notifications.v1.NotificationService.GetPreferences:input_type -> notifications.v1.GetPreferencesRequest
	24, // 41: notifications.v1.NotificationService.UpdatePreferences:input_type -> notifications.v1.UpdatePreferencesRequest
	26, // 42: notifications.v1.NotificationService.StreamNotifications:input_type -> notifications.v1.StreamNotificationsRequest
	9,  // 43: notifications.v1.NotificationService.RegisterDevice:output_type -> notifications.v1.RegisterDeviceResponse
	11, // 44: notifications.v1.NotificationService.UnregisterDevice:output_type -> notifications.v1.UnregisterDeviceResponse
	13, // 45: notifications.v1.NotificationService.GetNotification:output_type -> notifications.v1.GetNotificationResponse
	15, // 46: notifications.v1.NotificationService.ListNotifications:output_type -> notifications.v1.ListNotificationsResponse
	17, // 47: notifications.v1.NotificationService.MarkAsRead:output_type -> notifications.v1.MarkAsReadResponse
	19, // 48: notifications.v1.NotificationService.MarkAllAsRead:output_type -> notifications.v1.MarkAllAsReadResponse
	21, // 49: notifications.v1.NotificationService.DeleteNotification:output_type -> notifications.v1.DeleteNotificationResponse
	23, // 50: notifications.v1.NotificationService.GetPreferences:output_type -> notifications.v1.GetPreferencesResponse
	25, // 51: notifications.v1.NotificationService.UpdatePreferences:output_type -> notifications.v1.UpdatePreferencesResponse
	7,  // 52: notifications.v1.NotificationService.StreamNotifications:output_type -> notifications.v1.NotificationEvent
	43, // [43:53] is the sub-list for method output_type
	33, // [33:43] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_notifications_v1_notifications_proto_init() }
func file_notifications_v1_notifications_proto_init() {
	if File_notifications_v1_notifications_proto != nil {
		return
	}
	file_notifications_v1_notifications_proto_msgTypes[0].OneofWrappers = []any{}
	file_notifications_v1_notifications_proto_msgTypes[3].OneofWrappers = []any{}
	file_notifications_v1_notifications_proto_msgTypes[12].OneofWrappers = []any{}
	file_notifications_v1_notifications_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_v1_notifications_proto_rawDesc), len(file_notifications_v1_notifications_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_v1_notifications_proto_depIdxs,
		EnumInfos:         file_notifications_v1_notifications_proto_enumTypes,
		MessageInfos:      file_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_notifications_v1_notifications_proto = out.File
	file_notifications_v1_notifications_proto_goTypes = nil
	file_notifications_v1_notifications_proto_depIdxs = nil
}
