// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package flags

import (
	"github.com/0xsj/hexagonal-go/internal/flags/application/command"
	"github.com/0xsj/hexagonal-go/internal/flags/application/query"
	"github.com/0xsj/hexagonal-go/internal/flags/domain"
	"github.com/0xsj/hexagonal-go/internal/flags/infrastructure/repository"
	"github.com/0xsj/hexagonal-go/internal/flags/interface/http/admin"
	v1 "github.com/0xsj/hexagonal-go/internal/flags/interface/http/v1"
	"github.com/0xsj/hexagonal-go/pkg/database"
	"github.com/0xsj/hexagonal-go/pkg/messaging"
	"github.com/0xsj/hexagonal-go/pkg/observability/logger"
	"github.com/google/wire"
)

// Injectors from provider.go:

// ProvideModule wires up the complete Flags module.
func ProvideModule(db database.DB, eventPublisher *messaging.DomainEventPublisher, log logger.Logger) (*v1.Handler, error) {
	postgresRepository := repository.NewPostgresRepository(db)
	createFlagCommand := command.NewCreateFlagCommand(postgresRepository, eventPublisher, log)
	updateFlagCommand := command.NewUpdateFlagCommand(postgresRepository, eventPublisher, log)
	deleteFlagCommand := command.NewDeleteFlagCommand(postgresRepository, eventPublisher, log)
	enableFlagCommand := command.NewEnableFlagCommand(postgresRepository, eventPublisher, log)
	disableFlagCommand := command.NewDisableFlagCommand(postgresRepository, eventPublisher, log)
	addRuleCommand := command.NewAddRuleCommand(postgresRepository, eventPublisher, log)
	removeRuleCommand := command.NewRemoveRuleCommand(postgresRepository, eventPublisher, log)
	setOverrideCommand := command.NewSetOverrideCommand(postgresRepository, eventPublisher, log)
	removeOverrideCommand := command.NewRemoveOverrideCommand(postgresRepository, eventPublisher, log)
	getFlagQuery := query.NewGetFlagQuery(postgresRepository)
	listFlagsQuery := query.NewListFlagsQuery(postgresRepository)
	evaluateFlagQuery := query.NewEvaluateFlagQuery(postgresRepository)
	handler := v1.NewHandler(createFlagCommand, updateFlagCommand, deleteFlagCommand, enableFlagCommand, disableFlagCommand, addRuleCommand, removeRuleCommand, setOverrideCommand, removeOverrideCommand, getFlagQuery, listFlagsQuery, evaluateFlagQuery, log)
	return handler, nil
}

// provider.go:

// FlagsSet provides all dependencies for the Flags domain.
var FlagsSet = wire.NewSet(repository.NewPostgresRepository, wire.Bind(new(domain.Repository), new(*repository.PostgresRepository)), command.NewCreateFlagCommand, command.NewUpdateFlagCommand, command.NewDeleteFlagCommand, command.NewEnableFlagCommand, command.NewDisableFlagCommand, command.NewAddRuleCommand, command.NewRemoveRuleCommand, command.NewSetOverrideCommand, command.NewRemoveOverrideCommand, query.NewGetFlagQuery, query.NewListFlagsQuery, query.NewEvaluateFlagQuery, v1.NewHandler, admin.NewHandler)
