// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: media/v1/media.proto

package mediav1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "github.com/0xsj/nexus/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Media type
type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_IMAGE       MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO       MediaType = 2
	MediaType_MEDIA_TYPE_AUDIO       MediaType = 3
	MediaType_MEDIA_TYPE_DOCUMENT    MediaType = 4
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_IMAGE",
		2: "MEDIA_TYPE_VIDEO",
		3: "MEDIA_TYPE_AUDIO",
		4: "MEDIA_TYPE_DOCUMENT",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_IMAGE":       1,
		"MEDIA_TYPE_VIDEO":       2,
		"MEDIA_TYPE_AUDIO":       3,
		"MEDIA_TYPE_DOCUMENT":    4,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_media_v1_media_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_media_v1_media_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{0}
}

// Processing status
type ProcessingStatus int32

const (
	ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED ProcessingStatus = 0
	ProcessingStatus_PROCESSING_STATUS_PENDING     ProcessingStatus = 1
	ProcessingStatus_PROCESSING_STATUS_PROCESSING  ProcessingStatus = 2
	ProcessingStatus_PROCESSING_STATUS_COMPLETED   ProcessingStatus = 3
	ProcessingStatus_PROCESSING_STATUS_FAILED      ProcessingStatus = 4
)

// Enum value maps for ProcessingStatus.
var (
	ProcessingStatus_name = map[int32]string{
		0: "PROCESSING_STATUS_UNSPECIFIED",
		1: "PROCESSING_STATUS_PENDING",
		2: "PROCESSING_STATUS_PROCESSING",
		3: "PROCESSING_STATUS_COMPLETED",
		4: "PROCESSING_STATUS_FAILED",
	}
	ProcessingStatus_value = map[string]int32{
		"PROCESSING_STATUS_UNSPECIFIED": 0,
		"PROCESSING_STATUS_PENDING":     1,
		"PROCESSING_STATUS_PROCESSING":  2,
		"PROCESSING_STATUS_COMPLETED":   3,
		"PROCESSING_STATUS_FAILED":      4,
	}
)

func (x ProcessingStatus) Enum() *ProcessingStatus {
	p := new(ProcessingStatus)
	*p = x
	return p
}

func (x ProcessingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_media_v1_media_proto_enumTypes[1].Descriptor()
}

func (ProcessingStatus) Type() protoreflect.EnumType {
	return &file_media_v1_media_proto_enumTypes[1]
}

func (x ProcessingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingStatus.Descriptor instead.
func (ProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{1}
}

// Upload method
type UploadMethod int32

const (
	UploadMethod_UPLOAD_METHOD_UNSPECIFIED UploadMethod = 0
	UploadMethod_UPLOAD_METHOD_DIRECT      UploadMethod = 1 // Direct to storage (S3, R2)
	UploadMethod_UPLOAD_METHOD_STREAMING   UploadMethod = 2 // Via gRPC stream
)

// Enum value maps for UploadMethod.
var (
	UploadMethod_name = map[int32]string{
		0: "UPLOAD_METHOD_UNSPECIFIED",
		1: "UPLOAD_METHOD_DIRECT",
		2: "UPLOAD_METHOD_STREAMING",
	}
	UploadMethod_value = map[string]int32{
		"UPLOAD_METHOD_UNSPECIFIED": 0,
		"UPLOAD_METHOD_DIRECT":      1,
		"UPLOAD_METHOD_STREAMING":   2,
	}
)

func (x UploadMethod) Enum() *UploadMethod {
	p := new(UploadMethod)
	*p = x
	return p
}

func (x UploadMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_media_v1_media_proto_enumTypes[2].Descriptor()
}

func (UploadMethod) Type() protoreflect.EnumType {
	return &file_media_v1_media_proto_enumTypes[2]
}

func (x UploadMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadMethod.Descriptor instead.
func (UploadMethod) EnumDescriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{2}
}

// Media resource
type Media struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type         MediaType              `protobuf:"varint,3,opt,name=type,proto3,enum=media.v1.MediaType" json:"type,omitempty"`
	Filename     string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType     string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes    int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Url          string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl string                 `protobuf:"bytes,8,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Status       ProcessingStatus       `protobuf:"varint,9,opt,name=status,proto3,enum=media.v1.ProcessingStatus" json:"status,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Media metadata
	Metadata *MediaMetadata `protobuf:"bytes,12,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	// Processing info
	Processing *ProcessingInfo `protobuf:"bytes,13,opt,name=processing,proto3,oneof" json:"processing,omitempty"`
	// Storage info
	StorageKey    string `protobuf:"bytes,14,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	StorageBucket string `protobuf:"bytes,15,opt,name=storage_bucket,json=storageBucket,proto3" json:"storage_bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Media) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *Media) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Media) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Media) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Media) GetStatus() ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (x *Media) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Media) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Media) GetMetadata() *MediaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Media) GetProcessing() *ProcessingInfo {
	if x != nil {
		return x.Processing
	}
	return nil
}

func (x *Media) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *Media) GetStorageBucket() string {
	if x != nil {
		return x.StorageBucket
	}
	return ""
}

// Media metadata
type MediaMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image/Video dimensions
	Width  *int32 `protobuf:"varint,1,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height *int32 `protobuf:"varint,2,opt,name=height,proto3,oneof" json:"height,omitempty"`
	// Video/Audio duration
	DurationSeconds *int32 `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3,oneof" json:"duration_seconds,omitempty"`
	// Bitrate (for video/audio)
	Bitrate *int32 `protobuf:"varint,4,opt,name=bitrate,proto3,oneof" json:"bitrate,omitempty"`
	// Format info
	Codec *string `protobuf:"bytes,5,opt,name=codec,proto3,oneof" json:"codec,omitempty"`
	// EXIF data (for images)
	Exif *ExifData `protobuf:"bytes,6,opt,name=exif,proto3,oneof" json:"exif,omitempty"`
	// File hash (for deduplication)
	Hash          *string `protobuf:"bytes,7,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaMetadata) Reset() {
	*x = MediaMetadata{}
	mi := &file_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMetadata) ProtoMessage() {}

func (x *MediaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMetadata.ProtoReflect.Descriptor instead.
func (*MediaMetadata) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *MediaMetadata) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *MediaMetadata) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *MediaMetadata) GetDurationSeconds() int32 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

func (x *MediaMetadata) GetBitrate() int32 {
	if x != nil && x.Bitrate != nil {
		return *x.Bitrate
	}
	return 0
}

func (x *MediaMetadata) GetCodec() string {
	if x != nil && x.Codec != nil {
		return *x.Codec
	}
	return ""
}

func (x *MediaMetadata) GetExif() *ExifData {
	if x != nil {
		return x.Exif
	}
	return nil
}

func (x *MediaMetadata) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

// EXIF data
type ExifData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraMake    *string                `protobuf:"bytes,1,opt,name=camera_make,json=cameraMake,proto3,oneof" json:"camera_make,omitempty"`
	CameraModel   *string                `protobuf:"bytes,2,opt,name=camera_model,json=cameraModel,proto3,oneof" json:"camera_model,omitempty"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=taken_at,json=takenAt,proto3,oneof" json:"taken_at,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,4,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,5,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Iso           *int32                 `protobuf:"varint,6,opt,name=iso,proto3,oneof" json:"iso,omitempty"`
	Aperture      *string                `protobuf:"bytes,7,opt,name=aperture,proto3,oneof" json:"aperture,omitempty"`
	ShutterSpeed  *string                `protobuf:"bytes,8,opt,name=shutter_speed,json=shutterSpeed,proto3,oneof" json:"shutter_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExifData) Reset() {
	*x = ExifData{}
	mi := &file_media_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExifData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExifData) ProtoMessage() {}

func (x *ExifData) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExifData.ProtoReflect.Descriptor instead.
func (*ExifData) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *ExifData) GetCameraMake() string {
	if x != nil && x.CameraMake != nil {
		return *x.CameraMake
	}
	return ""
}

func (x *ExifData) GetCameraModel() string {
	if x != nil && x.CameraModel != nil {
		return *x.CameraModel
	}
	return ""
}

func (x *ExifData) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *ExifData) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *ExifData) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *ExifData) GetIso() int32 {
	if x != nil && x.Iso != nil {
		return *x.Iso
	}
	return 0
}

func (x *ExifData) GetAperture() string {
	if x != nil && x.Aperture != nil {
		return *x.Aperture
	}
	return ""
}

func (x *ExifData) GetShutterSpeed() string {
	if x != nil && x.ShutterSpeed != nil {
		return *x.ShutterSpeed
	}
	return ""
}

// Processing info
type ProcessingInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             ProcessingStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=media.v1.ProcessingStatus" json:"status,omitempty"`
	ErrorMessage       *string                `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	ProgressPercentage int32                  `protobuf:"varint,3,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	// Generated variants
	Variants      []*MediaVariant `protobuf:"bytes,6,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingInfo) Reset() {
	*x = ProcessingInfo{}
	mi := &file_media_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingInfo) ProtoMessage() {}

func (x *ProcessingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingInfo.ProtoReflect.Descriptor instead.
func (*ProcessingInfo) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessingInfo) GetStatus() ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (x *ProcessingInfo) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *ProcessingInfo) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *ProcessingInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProcessingInfo) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ProcessingInfo) GetVariants() []*MediaVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

// Media variant (different sizes/formats)
type MediaVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "thumbnail", "small", "medium", "large"
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaVariant) Reset() {
	*x = MediaVariant{}
	mi := &file_media_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaVariant) ProtoMessage() {}

func (x *MediaVariant) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaVariant.ProtoReflect.Descriptor instead.
func (*MediaVariant) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *MediaVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaVariant) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaVariant) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaVariant) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaVariant) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Upload chunk (for streaming upload)
type UploadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadChunk_Metadata
	//	*UploadChunk_Chunk
	Data          isUploadChunk_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_media_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *UploadChunk) GetData() isUploadChunk_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadChunk) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadChunk) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadChunk_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadChunk_Data interface {
	isUploadChunk_Data()
}

type UploadChunk_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadChunk_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadChunk_Metadata) isUploadChunk_Data() {}

func (*UploadChunk_Chunk) isUploadChunk_Data() {}

// Upload metadata
type UploadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Type          MediaType              `protobuf:"varint,4,opt,name=type,proto3,enum=media.v1.MediaType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_media_v1_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *UploadMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadMetadata) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UploadMetadata) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

// Upload progress event
type UploadProgressEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MediaId            string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	BytesUploaded      int64                  `protobuf:"varint,2,opt,name=bytes_uploaded,json=bytesUploaded,proto3" json:"bytes_uploaded,omitempty"`
	TotalBytes         int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	ProgressPercentage int32                  `protobuf:"varint,4,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	Status             ProcessingStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=media.v1.ProcessingStatus" json:"status,omitempty"`
	ErrorMessage       *string                `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadProgressEvent) Reset() {
	*x = UploadProgressEvent{}
	mi := &file_media_v1_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProgressEvent) ProtoMessage() {}

func (x *UploadProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProgressEvent.ProtoReflect.Descriptor instead.
func (*UploadProgressEvent) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{7}
}

func (x *UploadProgressEvent) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *UploadProgressEvent) GetBytesUploaded() int64 {
	if x != nil {
		return x.BytesUploaded
	}
	return 0
}

func (x *UploadProgressEvent) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadProgressEvent) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *UploadProgressEvent) GetStatus() ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (x *UploadProgressEvent) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *UploadProgressEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetUploadURL
type GetUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Type          MediaType              `protobuf:"varint,4,opt,name=type,proto3,enum=media.v1.MediaType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLRequest) Reset() {
	*x = GetUploadURLRequest{}
	mi := &file_media_v1_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLRequest) ProtoMessage() {}

func (x *GetUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{8}
}

func (x *GetUploadURLRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetUploadURLRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetUploadURLRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *GetUploadURLRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

type GetUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	UploadHeaders map[string]string      `protobuf:"bytes,3,rep,name=upload_headers,json=uploadHeaders,proto3" json:"upload_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Headers to include in upload request
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLResponse) Reset() {
	*x = GetUploadURLResponse{}
	mi := &file_media_v1_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLResponse) ProtoMessage() {}

func (x *GetUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetUploadURLResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadURLResponse) GetUploadHeaders() map[string]string {
	if x != nil {
		return x.UploadHeaders
	}
	return nil
}

func (x *GetUploadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetUploadURLResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ConfirmUpload
type ConfirmUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Etag          *string                `protobuf:"bytes,2,opt,name=etag,proto3,oneof" json:"etag,omitempty"` // S3 ETag for validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_media_v1_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmUploadRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ConfirmUploadRequest) GetEtag() string {
	if x != nil && x.Etag != nil {
		return *x.Etag
	}
	return ""
}

type ConfirmUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadResponse) Reset() {
	*x = ConfirmUploadResponse{}
	mi := &file_media_v1_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadResponse) ProtoMessage() {}

func (x *ConfirmUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUploadResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmUploadResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *ConfirmUploadResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UploadMedia (response for streaming upload)
type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_media_v1_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{12}
}

func (x *UploadMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *UploadMediaResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetMedia
type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_media_v1_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{13}
}

func (x *GetMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_media_v1_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{14}
}

func (x *GetMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *GetMediaResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ListMedia
type ListMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Type          *MediaType             `protobuf:"varint,2,opt,name=type,proto3,enum=media.v1.MediaType,oneof" json:"type,omitempty"`
	Status        *ProcessingStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=media.v1.ProcessingStatus,oneof" json:"status,omitempty"`
	CreatedRange  *v1.TimeRange          `protobuf:"bytes,4,opt,name=created_range,json=createdRange,proto3,oneof" json:"created_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaRequest) Reset() {
	*x = ListMediaRequest{}
	mi := &file_media_v1_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaRequest) ProtoMessage() {}

func (x *ListMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaRequest.ProtoReflect.Descriptor instead.
func (*ListMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{15}
}

func (x *ListMediaRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMediaRequest) GetType() MediaType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *ListMediaRequest) GetStatus() ProcessingStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (x *ListMediaRequest) GetCreatedRange() *v1.TimeRange {
	if x != nil {
		return x.CreatedRange
	}
	return nil
}

type ListMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaResponse) Reset() {
	*x = ListMediaResponse{}
	mi := &file_media_v1_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaResponse) ProtoMessage() {}

func (x *ListMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaResponse.ProtoReflect.Descriptor instead.
func (*ListMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{16}
}

func (x *ListMediaResponse) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *ListMediaResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMediaResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DeleteMedia
type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_media_v1_media_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_media_v1_media_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteMediaResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ProcessMedia
type ProcessMediaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MediaId            string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Variants           []string               `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"` // ["thumbnail", "small", "medium", "large"]
	GenerateThumbnails *bool                  `protobuf:"varint,3,opt,name=generate_thumbnails,json=generateThumbnails,proto3,oneof" json:"generate_thumbnails,omitempty"`
	Optimize           *bool                  `protobuf:"varint,4,opt,name=optimize,proto3,oneof" json:"optimize,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessMediaRequest) Reset() {
	*x = ProcessMediaRequest{}
	mi := &file_media_v1_media_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMediaRequest) ProtoMessage() {}

func (x *ProcessMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMediaRequest.ProtoReflect.Descriptor instead.
func (*ProcessMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{19}
}

func (x *ProcessMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ProcessMediaRequest) GetVariants() []string {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *ProcessMediaRequest) GetGenerateThumbnails() bool {
	if x != nil && x.GenerateThumbnails != nil {
		return *x.GenerateThumbnails
	}
	return false
}

func (x *ProcessMediaRequest) GetOptimize() bool {
	if x != nil && x.Optimize != nil {
		return *x.Optimize
	}
	return false
}

type ProcessMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Processing    *ProcessingInfo        `protobuf:"bytes,2,opt,name=processing,proto3" json:"processing,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMediaResponse) Reset() {
	*x = ProcessMediaResponse{}
	mi := &file_media_v1_media_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMediaResponse) ProtoMessage() {}

func (x *ProcessMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMediaResponse.ProtoReflect.Descriptor instead.
func (*ProcessMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{20}
}

func (x *ProcessMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessMediaResponse) GetProcessing() *ProcessingInfo {
	if x != nil {
		return x.Processing
	}
	return nil
}

func (x *ProcessMediaResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetProcessingStatus
type GetProcessingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessingStatusRequest) Reset() {
	*x = GetProcessingStatusRequest{}
	mi := &file_media_v1_media_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingStatusRequest) ProtoMessage() {}

func (x *GetProcessingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessingStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProcessingStatusRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{21}
}

func (x *GetProcessingStatusRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type GetProcessingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processing    *ProcessingInfo        `protobuf:"bytes,1,opt,name=processing,proto3" json:"processing,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessingStatusResponse) Reset() {
	*x = GetProcessingStatusResponse{}
	mi := &file_media_v1_media_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingStatusResponse) ProtoMessage() {}

func (x *GetProcessingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessingStatusResponse.ProtoReflect.Descriptor instead.
func (*GetProcessingStatusResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{22}
}

func (x *GetProcessingStatusResponse) GetProcessing() *ProcessingInfo {
	if x != nil {
		return x.Processing
	}
	return nil
}

func (x *GetProcessingStatusResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StreamUploadProgress
type StreamUploadProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUploadProgressRequest) Reset() {
	*x = StreamUploadProgressRequest{}
	mi := &file_media_v1_media_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUploadProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUploadProgressRequest) ProtoMessage() {}

func (x *StreamUploadProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_media_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUploadProgressRequest.ProtoReflect.Descriptor instead.
func (*StreamUploadProgressRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_media_proto_rawDescGZIP(), []int{23}
}

func (x *StreamUploadProgressRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

var File_media_v1_media_proto protoreflect.FileDescriptor

const file_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x14media/v1/media.proto\x12\bmedia.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\xef\x04\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.media.v1.MediaTypeR\x04type\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\b \x01(\tR\fthumbnailUrl\x122\n" +
	"\x06status\x18\t \x01(\x0e2\x1a.media.v1.ProcessingStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\bmetadata\x18\f \x01(\v2\x17.media.v1.MediaMetadataH\x00R\bmetadata\x88\x01\x01\x12=\n" +
	"\n" +
	"processing\x18\r \x01(\v2\x18.media.v1.ProcessingInfoH\x01R\n" +
	"processing\x88\x01\x01\x12\x1f\n" +
	"\vstorage_key\x18\x0e \x01(\tR\n" +
	"storageKey\x12%\n" +
	"\x0estorage_bucket\x18\x0f \x01(\tR\rstorageBucketB\v\n" +
	"\t_metadataB\r\n" +
	"\v_processing\"\xc9\x02\n" +
	"\rMediaMetadata\x12\x19\n" +
	"\x05width\x18\x01 \x01(\x05H\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x02 \x01(\x05H\x01R\x06height\x88\x01\x01\x12.\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05H\x02R\x0fdurationSeconds\x88\x01\x01\x12\x1d\n" +
	"\abitrate\x18\x04 \x01(\x05H\x03R\abitrate\x88\x01\x01\x12\x19\n" +
	"\x05codec\x18\x05 \x01(\tH\x04R\x05codec\x88\x01\x01\x12+\n" +
	"\x04exif\x18\x06 \x01(\v2\x12.media.v1.ExifDataH\x05R\x04exif\x88\x01\x01\x12\x17\n" +
	"\x04hash\x18\a \x01(\tH\x06R\x04hash\x88\x01\x01B\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\x13\n" +
	"\x11_duration_secondsB\n" +
	"\n" +
	"\b_bitrateB\b\n" +
	"\x06_codecB\a\n" +
	"\x05_exifB\a\n" +
	"\x05_hash\"\xaa\x03\n" +
	"\bExifData\x12$\n" +
	"\vcamera_make\x18\x01 \x01(\tH\x00R\n" +
	"cameraMake\x88\x01\x01\x12&\n" +
	"\fcamera_model\x18\x02 \x01(\tH\x01R\vcameraModel\x88\x01\x01\x12:\n" +
	"\btaken_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\atakenAt\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\x04 \x01(\x01H\x03R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x05 \x01(\x01H\x04R\tlongitude\x88\x01\x01\x12\x15\n" +
	"\x03iso\x18\x06 \x01(\x05H\x05R\x03iso\x88\x01\x01\x12\x1f\n" +
	"\baperture\x18\a \x01(\tH\x06R\baperture\x88\x01\x01\x12(\n" +
	"\rshutter_speed\x18\b \x01(\tH\aR\fshutterSpeed\x88\x01\x01B\x0e\n" +
	"\f_camera_makeB\x0f\n" +
	"\r_camera_modelB\v\n" +
	"\t_taken_atB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\x06\n" +
	"\x04_isoB\v\n" +
	"\t_apertureB\x10\n" +
	"\x0e_shutter_speed\"\xf5\x02\n" +
	"\x0eProcessingInfo\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.media.v1.ProcessingStatusR\x06status\x12(\n" +
	"\rerror_message\x18\x02 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12/\n" +
	"\x13progress_percentage\x18\x03 \x01(\x05R\x12progressPercentage\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12B\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01\x122\n" +
	"\bvariants\x18\x06 \x03(\v2\x16.media.v1.MediaVariantR\bvariantsB\x10\n" +
	"\x0e_error_messageB\x0f\n" +
	"\r_completed_at\"\x81\x01\n" +
	"\fMediaVariant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\"e\n" +
	"\vUploadChunk\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.media.v1.UploadMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x91\x01\n" +
	"\x0eUploadMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.media.v1.MediaTypeR\x04type\"\xd3\x02\n" +
	"\x13UploadProgressEvent\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12%\n" +
	"\x0ebytes_uploaded\x18\x02 \x01(\x03R\rbytesUploaded\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12/\n" +
	"\x13progress_percentage\x18\x04 \x01(\x05R\x12progressPercentage\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.media.v1.ProcessingStatusR\x06status\x12(\n" +
	"\rerror_message\x18\x06 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\x10\n" +
	"\x0e_error_message\"\x96\x01\n" +
	"\x13GetUploadURLRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.media.v1.MediaTypeR\x04type\"\xe0\x02\n" +
	"\x14GetUploadURLResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12X\n" +
	"\x0eupload_headers\x18\x03 \x03(\v21.media.v1.GetUploadURLResponse.UploadHeadersEntryR\ruploadHeaders\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\x1a@\n" +
	"\x12UploadHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x14ConfirmUploadRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x17\n" +
	"\x04etag\x18\x02 \x01(\tH\x00R\x04etag\x88\x01\x01B\a\n" +
	"\x05_etag\"w\n" +
	"\x15ConfirmUploadResponse\x12%\n" +
	"\x05media\x18\x01 \x01(\v2\x0f.media.v1.MediaR\x05media\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"u\n" +
	"\x13UploadMediaResponse\x12%\n" +
	"\x05media\x18\x01 \x01(\v2\x0f.media.v1.MediaR\x05media\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\",\n" +
	"\x0fGetMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"r\n" +
	"\x10GetMediaResponse\x12%\n" +
	"\x05media\x18\x01 \x01(\v2\x0f.media.v1.MediaR\x05media\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x9d\x02\n" +
	"\x10ListMediaRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.media.v1.MediaTypeH\x00R\x04type\x88\x01\x01\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.media.v1.ProcessingStatusH\x01R\x06status\x88\x01\x01\x12>\n" +
	"\rcreated_range\x18\x04 \x01(\v2\x14.common.v1.TimeRangeH\x02R\fcreatedRange\x88\x01\x01B\a\n" +
	"\x05_typeB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_created_range\"\xb2\x01\n" +
	"\x11ListMediaResponse\x12%\n" +
	"\x05media\x18\x01 \x03(\v2\x0f.media.v1.MediaR\x05media\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"/\n" +
	"\x12DeleteMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"h\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\xc8\x01\n" +
	"\x13ProcessMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1a\n" +
	"\bvariants\x18\x02 \x03(\tR\bvariants\x124\n" +
	"\x13generate_thumbnails\x18\x03 \x01(\bH\x00R\x12generateThumbnails\x88\x01\x01\x12\x1f\n" +
	"\boptimize\x18\x04 \x01(\bH\x01R\boptimize\x88\x01\x01B\x16\n" +
	"\x14_generate_thumbnailsB\v\n" +
	"\t_optimize\"\xa3\x01\n" +
	"\x14ProcessMediaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\n" +
	"processing\x18\x02 \x01(\v2\x18.media.v1.ProcessingInfoR\n" +
	"processing\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"7\n" +
	"\x1aGetProcessingStatusRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\x90\x01\n" +
	"\x1bGetProcessingStatusResponse\x128\n" +
	"\n" +
	"processing\x18\x01 \x01(\v2\x18.media.v1.ProcessingInfoR\n" +
	"processing\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"8\n" +
	"\x1bStreamUploadProgressRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId*\x82\x01\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x02\x12\x14\n" +
	"\x10MEDIA_TYPE_AUDIO\x10\x03\x12\x17\n" +
	"\x13MEDIA_TYPE_DOCUMENT\x10\x04*\xb5\x01\n" +
	"\x10ProcessingStatus\x12!\n" +
	"\x1dPROCESSING_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PROCESSING_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cPROCESSING_STATUS_PROCESSING\x10\x02\x12\x1f\n" +
	"\x1bPROCESSING_STATUS_COMPLETED\x10\x03\x12\x1c\n" +
	"\x18PROCESSING_STATUS_FAILED\x10\x04*d\n" +
	"\fUploadMethod\x12\x1d\n" +
	"\x19UPLOAD_METHOD_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14UPLOAD_METHOD_DIRECT\x10\x01\x12\x1b\n" +
	"\x17UPLOAD_METHOD_STREAMING\x10\x022\xee\a\n" +
	"\fMediaService\x12n\n" +
	"\fGetUploadURL\x12\x1d.media.v1.GetUploadURLRequest\x1a\x1e.media.v1.GetUploadURLResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/media/upload-url\x12y\n" +
	"\rConfirmUpload\x12\x1e.media.v1.ConfirmUploadRequest\x1a\x1f.media.v1.ConfirmUploadResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/media/{media_id}/confirm\x12E\n" +
	"\vUploadMedia\x12\x15.media.v1.UploadChunk\x1a\x1d.media.v1.UploadMediaResponse(\x01\x12_\n" +
	"\bGetMedia\x12\x19.media.v1.GetMediaRequest\x1a\x1a.media.v1.GetMediaResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/media/{media_id}\x12W\n" +
	"\tListMedia\x12\x1a.media.v1.ListMediaRequest\x1a\x1b.media.v1.ListMediaResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/media\x12h\n" +
	"\vDeleteMedia\x12\x1c.media.v1.DeleteMediaRequest\x1a\x1d.media.v1.DeleteMediaResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/media/{media_id}\x12v\n" +
	"\fProcessMedia\x12\x1d.media.v1.ProcessMediaRequest\x1a\x1e.media.v1.ProcessMediaResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/media/{media_id}/process\x12\x87\x01\n" +
	"\x13GetProcessingStatus\x12$.media.v1.GetProcessingStatusRequest\x1a%.media.v1.GetProcessingStatusResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/media/{media_id}/status\x12\x85\x01\n" +
	"\x14StreamUploadProgress\x12%.media.v1.StreamUploadProgressRequest\x1a\x1d.media.v1.UploadProgressEvent\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/media/{media_id}/progress0\x01B\x87\x01\n" +
	"\fcom.media.v1B\n" +
	"MediaProtoP\x01Z*github.com/0xsj/nexus/api/media/v1;mediav1\xa2\x02\x03MXX\xaa\x02\bMedia.V1\xca\x02\bMedia\\V1\xe2\x02\x14Media\\V1\\GPBMetadata\xea\x02\tMedia::V1b\x06proto3"

var (
	file_media_v1_media_proto_rawDescOnce sync.Once
	file_media_v1_media_proto_rawDescData []byte
)

func file_media_v1_media_proto_rawDescGZIP() []byte {
	file_media_v1_media_proto_rawDescOnce.Do(func() {
		file_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_v1_media_proto_rawDesc), len(file_media_v1_media_proto_rawDesc)))
	})
	return file_media_v1_media_proto_rawDescData
}

var file_media_v1_media_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_media_v1_media_proto_goTypes = []any{
	(MediaType)(0),                      // 0: media.v1.MediaType
	(ProcessingStatus)(0),               // 1: media.v1.ProcessingStatus
	(UploadMethod)(0),                   // 2: media.v1.UploadMethod
	(*Media)(nil),                       // 3: media.v1.Media
	(*MediaMetadata)(nil),               // 4: media.v1.MediaMetadata
	(*ExifData)(nil),                    // 5: media.v1.ExifData
	(*ProcessingInfo)(nil),              // 6: media.v1.ProcessingInfo
	(*MediaVariant)(nil),                // 7: media.v1.MediaVariant
	(*UploadChunk)(nil),                 // 8: media.v1.UploadChunk
	(*UploadMetadata)(nil),              // 9: media.v1.UploadMetadata
	(*UploadProgressEvent)(nil),         // 10: media.v1.UploadProgressEvent
	(*GetUploadURLRequest)(nil),         // 11: media.v1.GetUploadURLRequest
	(*GetUploadURLResponse)(nil),        // 12: media.v1.GetUploadURLResponse
	(*ConfirmUploadRequest)(nil),        // 13: media.v1.ConfirmUploadRequest
	(*ConfirmUploadResponse)(nil),       // 14: media.v1.ConfirmUploadResponse
	(*UploadMediaResponse)(nil),         // 15: media.v1.UploadMediaResponse
	(*GetMediaRequest)(nil),             // 16: media.v1.GetMediaRequest
	(*GetMediaResponse)(nil),            // 17: media.v1.GetMediaResponse
	(*ListMediaRequest)(nil),            // 18: media.v1.ListMediaRequest
	(*ListMediaResponse)(nil),           // 19: media.v1.ListMediaResponse
	(*DeleteMediaRequest)(nil),          // 20: media.v1.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),         // 21: media.v1.DeleteMediaResponse
	(*ProcessMediaRequest)(nil),         // 22: media.v1.ProcessMediaRequest
	(*ProcessMediaResponse)(nil),        // 23: media.v1.ProcessMediaResponse
	(*GetProcessingStatusRequest)(nil),  // 24: media.v1.GetProcessingStatusRequest
	(*GetProcessingStatusResponse)(nil), // 25: media.v1.GetProcessingStatusResponse
	(*StreamUploadProgressRequest)(nil), // 26: media.v1.StreamUploadProgressRequest
	nil,                                 // 27: media.v1.GetUploadURLResponse.UploadHeadersEntry
	(*timestamppb.Timestamp)(nil),       // 28: google.protobuf.Timestamp
	(*v1.ResponseMetadata)(nil),         // 29: common.v1.ResponseMetadata
	(*v1.PaginationRequest)(nil),        // 30: common.v1.PaginationRequest
	(*v1.TimeRange)(nil),                // 31: common.v1.TimeRange
	(*v1.PaginationResponse)(nil),       // 32: common.v1.PaginationResponse
}
var file_media_v1_media_proto_depIdxs = []int32{
	0,  // 0: media.v1.Media.type:type_name -> media.v1.MediaType
	1,  // 1: media.v1.Media.status:type_name -> media.v1.ProcessingStatus
	28, // 2: media.v1.Media.created_at:type_name -> google.protobuf.Timestamp
	28, // 3: media.v1.Media.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 4: media.v1.Media.metadata:type_name -> media.v1.MediaMetadata
	6,  // 5: media.v1.Media.processing:type_name -> media.v1.ProcessingInfo
	5,  // 6: media.v1.MediaMetadata.exif:type_name -> media.v1.ExifData
	28, // 7: media.v1.ExifData.taken_at:type_name -> google.protobuf.Timestamp
	1,  // 8: media.v1.ProcessingInfo.status:type_name -> media.v1.ProcessingStatus
	28, // 9: media.v1.ProcessingInfo.started_at:type_name -> google.protobuf.Timestamp
	28, // 10: media.v1.ProcessingInfo.completed_at:type_name -> google.protobuf.Timestamp
	7,  // 11: media.v1.ProcessingInfo.variants:type_name -> media.v1.MediaVariant
	9,  // 12: media.v1.UploadChunk.metadata:type_name -> media.v1.UploadMetadata
	0,  // 13: media.v1.UploadMetadata.type:type_name -> media.v1.MediaType
	1,  // 14: media.v1.UploadProgressEvent.status:type_name -> media.v1.ProcessingStatus
	28, // 15: media.v1.UploadProgressEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 16: media.v1.GetUploadURLRequest.type:type_name -> media.v1.MediaType
	27, // 17: media.v1.GetUploadURLResponse.upload_headers:type_name -> media.v1.GetUploadURLResponse.UploadHeadersEntry
	28, // 18: media.v1.GetUploadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	29, // 19: media.v1.GetUploadURLResponse.metadata:type_name -> common.v1.ResponseMetadata
	3,  // 20: media.v1.ConfirmUploadResponse.media:type_name -> media.v1.Media
	29, // 21: media.v1.ConfirmUploadResponse.metadata:type_name -> common.v1.ResponseMetadata
	3,  // 22: media.v1.UploadMediaResponse.media:type_name -> media.v1.Media
	29, // 23: media.v1.UploadMediaResponse.metadata:type_name -> common.v1.ResponseMetadata
	3,  // 24: media.v1.GetMediaResponse.media:type_name -> media.v1.Media
	29, // 25: media.v1.GetMediaResponse.metadata:type_name -> common.v1.ResponseMetadata
	30, // 26: media.v1.ListMediaRequest.pagination:type_name -> common.v1.PaginationRequest
	0,  // 27: media.v1.ListMediaRequest.type:type_name -> media.v1.MediaType
	1,  // 28: media.v1.ListMediaRequest.status:type_name -> media.v1.ProcessingStatus
	31, // 29: media.v1.ListMediaRequest.created_range:type_name -> common.v1.TimeRange
	3,  // 30: media.v1.ListMediaResponse.media:type_name -> media.v1.Media
	32, // 31: media.v1.ListMediaResponse.pagination:type_name -> common.v1.PaginationResponse
	29, // 32: media.v1.ListMediaResponse.metadata:type_name -> common.v1.ResponseMetadata
	29, // 33: media.v1.DeleteMediaResponse.metadata:type_name -> common.v1.ResponseMetadata
	6,  // 34: media.v1.ProcessMediaResponse.processing:type_name -> media.v1.ProcessingInfo
	29, // 35: media.v1.ProcessMediaResponse.metadata:type_name -> common.v1.ResponseMetadata
	6,  // 36: media.v1.GetProcessingStatusResponse.processing:type_name -> media.v1.ProcessingInfo
	29, // 37: media.v1.GetProcessingStatusResponse.metadata:type_name -> common.v1.ResponseMetadata
	11, // 38: media.v1.MediaService.GetUploadURL:input_type -> media.v1.GetUploadURLRequest
	13, // 39: media.v1.MediaService.ConfirmUpload:input_type -> media.v1.ConfirmUploadRequest
	8,  // 40: media.v1.MediaService.UploadMedia:input_type -> media.v1.UploadChunk
	16, // 41: media.v1.MediaService.GetMedia:input_type -> media.v1.GetMediaRequest
	18, // 42: media.v1.MediaService.ListMedia:input_type -> media.v1.ListMediaRequest
	20, // 43: media.v1.MediaService.DeleteMedia:input_type -> media.v1.DeleteMediaRequest
	22, // 44: media.v1.MediaService.ProcessMedia:input_type -> media.v1.ProcessMediaRequest
	24, // 45: media.v1.MediaService.GetProcessingStatus:input_type -> media.v1.GetProcessingStatusRequest
	26, // 46: media.v1.MediaService.StreamUploadProgress:input_type -> media.v1.StreamUploadProgressRequest
	12, // 47: media.v1.MediaService.GetUploadURL:output_type -> media.v1.GetUploadURLResponse
	14, // 48: media.v1.MediaService.ConfirmUpload:output_type -> media.v1.ConfirmUploadResponse
	15, // 49: media.v1.MediaService.UploadMedia:output_type -> media.v1.UploadMediaResponse
	17, // 50: media.v1.MediaService.GetMedia:output_type -> media.v1.GetMediaResponse
	19, // 51: media.v1.MediaService.ListMedia:output_type -> media.v1.ListMediaResponse
	21, // 52: media.v1.MediaService.DeleteMedia:output_type -> media.v1.DeleteMediaResponse
	23, // 53: media.v1.MediaService.ProcessMedia:output_type -> media.v1.ProcessMediaResponse
	25, // 54: media.v1.MediaService.GetProcessingStatus:output_type -> media.v1.GetProcessingStatusResponse
	10, // 55: media.v1.MediaService.StreamUploadProgress:output_type -> media.v1.UploadProgressEvent
	47, // [47:56] is the sub-list for method output_type
	38, // [38:47] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_media_v1_media_proto_init() }
func file_media_v1_media_proto_init() {
	if File_media_v1_media_proto != nil {
		return
	}
	file_media_v1_media_proto_msgTypes[0].OneofWrappers = []any{}
	file_media_v1_media_proto_msgTypes[1].OneofWrappers = []any{}
	file_media_v1_media_proto_msgTypes[2].OneofWrappers = []any{}
	file_media_v1_media_proto_msgTypes[3].OneofWrappers = []any{}
	file_media_v1_media_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadChunk_Metadata)(nil),
		(*UploadChunk_Chunk)(nil),
	}
	file_media_v1_media_proto_msgTypes[7].OneofWrappers = []any{}
	file_media_v1_media_proto_msgTypes[10].OneofWrappers = []any{}
	file_media_v1_media_proto_msgTypes[15].OneofWrappers = []any{}
	file_media_v1_media_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_media_proto_rawDesc), len(file_media_v1_media_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_v1_media_proto_goTypes,
		DependencyIndexes: file_media_v1_media_proto_depIdxs,
		EnumInfos:         file_media_v1_media_proto_enumTypes,
		MessageInfos:      file_media_v1_media_proto_msgTypes,
	}.Build()
	File_media_v1_media_proto = out.File
	file_media_v1_media_proto_goTypes = nil
	file_media_v1_media_proto_depIdxs = nil
}
