// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "github.com/0xsj/nexus/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OAuth provider
type OAuthProvider int32

const (
	OAuthProvider_OAUTH_PROVIDER_UNSPECIFIED OAuthProvider = 0
	OAuthProvider_OAUTH_PROVIDER_GOOGLE      OAuthProvider = 1
	OAuthProvider_OAUTH_PROVIDER_APPLE       OAuthProvider = 2
	OAuthProvider_OAUTH_PROVIDER_GITHUB      OAuthProvider = 3
)

// Enum value maps for OAuthProvider.
var (
	OAuthProvider_name = map[int32]string{
		0: "OAUTH_PROVIDER_UNSPECIFIED",
		1: "OAUTH_PROVIDER_GOOGLE",
		2: "OAUTH_PROVIDER_APPLE",
		3: "OAUTH_PROVIDER_GITHUB",
	}
	OAuthProvider_value = map[string]int32{
		"OAUTH_PROVIDER_UNSPECIFIED": 0,
		"OAUTH_PROVIDER_GOOGLE":      1,
		"OAUTH_PROVIDER_APPLE":       2,
		"OAUTH_PROVIDER_GITHUB":      3,
	}
)

func (x OAuthProvider) Enum() *OAuthProvider {
	p := new(OAuthProvider)
	*p = x
	return p
}

func (x OAuthProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OAuthProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (OAuthProvider) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[0]
}

func (x OAuthProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OAuthProvider.Descriptor instead.
func (OAuthProvider) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

// Session information
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveAt  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,10,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Session) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Session) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetLastActiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Session) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

// Token pair (access + refresh)
type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds until access token expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// LoginWithPassword
type LoginWithPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientContext *v1.ClientContext      `protobuf:"bytes,10,opt,name=client_context,json=clientContext,proto3" json:"client_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithPasswordRequest) Reset() {
	*x = LoginWithPasswordRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithPasswordRequest) ProtoMessage() {}

func (x *LoginWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginWithPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginWithPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginWithPasswordRequest) GetClientContext() *v1.ClientContext {
	if x != nil {
		return x.ClientContext
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Session       *Session               `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *LoginResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SendMagicLink
type SendMagicLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ClientContext *v1.ClientContext      `protobuf:"bytes,10,opt,name=client_context,json=clientContext,proto3" json:"client_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMagicLinkRequest) Reset() {
	*x = SendMagicLinkRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMagicLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMagicLinkRequest) ProtoMessage() {}

func (x *SendMagicLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMagicLinkRequest.ProtoReflect.Descriptor instead.
func (*SendMagicLinkRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SendMagicLinkRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendMagicLinkRequest) GetClientContext() *v1.ClientContext {
	if x != nil {
		return x.ClientContext
	}
	return nil
}

type SendMagicLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // "Magic link sent to your email"
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMagicLinkResponse) Reset() {
	*x = SendMagicLinkResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMagicLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMagicLinkResponse) ProtoMessage() {}

func (x *SendMagicLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMagicLinkResponse.ProtoReflect.Descriptor instead.
func (*SendMagicLinkResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SendMagicLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMagicLinkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMagicLinkResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// VerifyMagicLink
type VerifyMagicLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ClientContext *v1.ClientContext      `protobuf:"bytes,10,opt,name=client_context,json=clientContext,proto3" json:"client_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMagicLinkRequest) Reset() {
	*x = VerifyMagicLinkRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMagicLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMagicLinkRequest) ProtoMessage() {}

func (x *VerifyMagicLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMagicLinkRequest.ProtoReflect.Descriptor instead.
func (*VerifyMagicLinkRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyMagicLinkRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyMagicLinkRequest) GetClientContext() *v1.ClientContext {
	if x != nil {
		return x.ClientContext
	}
	return nil
}

// InitiateOAuth
type InitiateOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      OAuthProvider          `protobuf:"varint,1,opt,name=provider,proto3,enum=auth.v1.OAuthProvider" json:"provider,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	ClientContext *v1.ClientContext      `protobuf:"bytes,10,opt,name=client_context,json=clientContext,proto3" json:"client_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateOAuthRequest) Reset() {
	*x = InitiateOAuthRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateOAuthRequest) ProtoMessage() {}

func (x *InitiateOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateOAuthRequest.ProtoReflect.Descriptor instead.
func (*InitiateOAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *InitiateOAuthRequest) GetProvider() OAuthProvider {
	if x != nil {
		return x.Provider
	}
	return OAuthProvider_OAUTH_PROVIDER_UNSPECIFIED
}

func (x *InitiateOAuthRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *InitiateOAuthRequest) GetClientContext() *v1.ClientContext {
	if x != nil {
		return x.ClientContext
	}
	return nil
}

type InitiateOAuthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // CSRF token
	Metadata         *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitiateOAuthResponse) Reset() {
	*x = InitiateOAuthResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateOAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateOAuthResponse) ProtoMessage() {}

func (x *InitiateOAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateOAuthResponse.ProtoReflect.Descriptor instead.
func (*InitiateOAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *InitiateOAuthResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *InitiateOAuthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InitiateOAuthResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CompleteOAuth
type CompleteOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      OAuthProvider          `protobuf:"varint,1,opt,name=provider,proto3,enum=auth.v1.OAuthProvider" json:"provider,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ClientContext *v1.ClientContext      `protobuf:"bytes,10,opt,name=client_context,json=clientContext,proto3" json:"client_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOAuthRequest) Reset() {
	*x = CompleteOAuthRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOAuthRequest) ProtoMessage() {}

func (x *CompleteOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOAuthRequest.ProtoReflect.Descriptor instead.
func (*CompleteOAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteOAuthRequest) GetProvider() OAuthProvider {
	if x != nil {
		return x.Provider
	}
	return OAuthProvider_OAUTH_PROVIDER_UNSPECIFIED
}

func (x *CompleteOAuthRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteOAuthRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CompleteOAuthRequest) GetClientContext() *v1.ClientContext {
	if x != nil {
		return x.ClientContext
	}
	return nil
}

// RefreshToken
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *RefreshTokenResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Logout
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// LogoutAll
type LogoutAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutAllRequest) Reset() {
	*x = LogoutAllRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAllRequest) ProtoMessage() {}

func (x *LogoutAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAllRequest.ProtoReflect.Descriptor instead.
func (*LogoutAllRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

type LogoutAllResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionsInvalidated int32                  `protobuf:"varint,2,opt,name=sessions_invalidated,json=sessionsInvalidated,proto3" json:"sessions_invalidated,omitempty"`
	Metadata            *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LogoutAllResponse) Reset() {
	*x = LogoutAllResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAllResponse) ProtoMessage() {}

func (x *LogoutAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAllResponse.ProtoReflect.Descriptor instead.
func (*LogoutAllResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *LogoutAllResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutAllResponse) GetSessionsInvalidated() int32 {
	if x != nil {
		return x.SessionsInvalidated
	}
	return 0
}

func (x *LogoutAllResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetSession
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSessionResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ListSessions
type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Metadata      *v1.ResponseMetadata   `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\x94\x03\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\x0elast_active_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastActiveAt\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"is_current\x18\n" +
	" \x01(\bR\tisCurrent\"r\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"\x8d\x01\n" +
	"\x18LoginWithPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12?\n" +
	"\x0eclient_context\x18\n" +
	" \x01(\v2\x18.common.v1.ClientContextR\rclientContext\"\xb9\x01\n" +
	"\rLoginResponse\x12*\n" +
	"\x06tokens\x18\x01 \x01(\v2\x12.auth.v1.TokenPairR\x06tokens\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\asession\x18\x03 \x01(\v2\x10.auth.v1.SessionR\asession\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"m\n" +
	"\x14SendMagicLinkRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12?\n" +
	"\x0eclient_context\x18\n" +
	" \x01(\v2\x18.common.v1.ClientContextR\rclientContext\"\x84\x01\n" +
	"\x15SendMagicLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"o\n" +
	"\x16VerifyMagicLinkRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12?\n" +
	"\x0eclient_context\x18\n" +
	" \x01(\v2\x18.common.v1.ClientContextR\rclientContext\"\xae\x01\n" +
	"\x14InitiateOAuthRequest\x122\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x16.auth.v1.OAuthProviderR\bprovider\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x12?\n" +
	"\x0eclient_context\x18\n" +
	" \x01(\v2\x18.common.v1.ClientContextR\rclientContext\"\x93\x01\n" +
	"\x15InitiateOAuthResponse\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\xb5\x01\n" +
	"\x14CompleteOAuthRequest\x122\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x16.auth.v1.OAuthProviderR\bprovider\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12?\n" +
	"\x0eclient_context\x18\n" +
	" \x01(\v2\x18.common.v1.ClientContextR\rclientContext\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"{\n" +
	"\x14RefreshTokenResponse\x12*\n" +
	"\x06tokens\x18\x01 \x01(\v2\x12.auth.v1.TokenPairR\x06tokens\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x0f\n" +
	"\rLogoutRequest\"c\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x12\n" +
	"\x10LogoutAllRequest\"\x99\x01\n" +
	"\x11LogoutAllResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x14sessions_invalidated\x18\x02 \x01(\x05R\x13sessionsInvalidated\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x13\n" +
	"\x11GetSessionRequest\"y\n" +
	"\x12GetSessionResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.auth.v1.SessionR\asession\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata\"\x15\n" +
	"\x13ListSessionsRequest\"}\n" +
	"\x14ListSessionsResponse\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.auth.v1.SessionR\bsessions\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadata*\x7f\n" +
	"\rOAuthProvider\x12\x1e\n" +
	"\x1aOAUTH_PROVIDER_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OAUTH_PROVIDER_GOOGLE\x10\x01\x12\x18\n" +
	"\x14OAUTH_PROVIDER_APPLE\x10\x02\x12\x19\n" +
	"\x15OAUTH_PROVIDER_GITHUB\x10\x032\xc1\b\n" +
	"\vAuthService\x12i\n" +
	"\x11LoginWithPassword\x12!.auth.v1.LoginWithPasswordRequest\x1a\x16.auth.v1.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12s\n" +
	"\rSendMagicLink\x12\x1d.auth.v1.SendMagicLinkRequest\x1a\x1e.auth.v1.SendMagicLinkResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/auth/magic-link/send\x12q\n" +
	"\x0fVerifyMagicLink\x12\x1f.auth.v1.VerifyMagicLinkRequest\x1a\x16.auth.v1.LoginResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/auth/magic-link/verify\x12z\n" +
	"\rInitiateOAuth\x12\x1d.auth.v1.InitiateOAuthRequest\x1a\x1e.auth.v1.InitiateOAuthResponse\"*\x82\xd3\xe4\x93\x02$\"\"/v1/auth/oauth/{provider}/initiate\x12u\n" +
	"\rCompleteOAuth\x12\x1d.auth.v1.CompleteOAuthRequest\x1a\x16.auth.v1.LoginResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/auth/oauth/{provider}/callback\x12h\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x1d.auth.v1.RefreshTokenResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12U\n" +
	"\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x17.auth.v1.LogoutResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12b\n" +
	"\tLogoutAll\x12\x19.auth.v1.LogoutAllRequest\x1a\x1a.auth.v1.LogoutAllResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/auth/logout-all\x12_\n" +
	"\n" +
	"GetSession\x12\x1a.auth.v1.GetSessionRequest\x1a\x1b.auth.v1.GetSessionResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/auth/session\x12f\n" +
	"\fListSessions\x12\x1c.auth.v1.ListSessionsRequest\x1a\x1d.auth.v1.ListSessionsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/auth/sessionsB\x7f\n" +
	"\vcom.auth.v1B\tAuthProtoP\x01Z(github.com/0xsj/nexus/api/auth/v1;authv1\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_auth_v1_auth_proto_goTypes = []any{
	(OAuthProvider)(0),               // 0: auth.v1.OAuthProvider
	(*Session)(nil),                  // 1: auth.v1.Session
	(*TokenPair)(nil),                // 2: auth.v1.TokenPair
	(*LoginWithPasswordRequest)(nil), // 3: auth.v1.LoginWithPasswordRequest
	(*LoginResponse)(nil),            // 4: auth.v1.LoginResponse
	(*SendMagicLinkRequest)(nil),     // 5: auth.v1.SendMagicLinkRequest
	(*SendMagicLinkResponse)(nil),    // 6: auth.v1.SendMagicLinkResponse
	(*VerifyMagicLinkRequest)(nil),   // 7: auth.v1.VerifyMagicLinkRequest
	(*InitiateOAuthRequest)(nil),     // 8: auth.v1.InitiateOAuthRequest
	(*InitiateOAuthResponse)(nil),    // 9: auth.v1.InitiateOAuthResponse
	(*CompleteOAuthRequest)(nil),     // 10: auth.v1.CompleteOAuthRequest
	(*RefreshTokenRequest)(nil),      // 11: auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),     // 12: auth.v1.RefreshTokenResponse
	(*LogoutRequest)(nil),            // 13: auth.v1.LogoutRequest
	(*LogoutResponse)(nil),           // 14: auth.v1.LogoutResponse
	(*LogoutAllRequest)(nil),         // 15: auth.v1.LogoutAllRequest
	(*LogoutAllResponse)(nil),        // 16: auth.v1.LogoutAllResponse
	(*GetSessionRequest)(nil),        // 17: auth.v1.GetSessionRequest
	(*GetSessionResponse)(nil),       // 18: auth.v1.GetSessionResponse
	(*ListSessionsRequest)(nil),      // 19: auth.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),     // 20: auth.v1.ListSessionsResponse
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
	(*v1.ClientContext)(nil),         // 22: common.v1.ClientContext
	(*v1.ResponseMetadata)(nil),      // 23: common.v1.ResponseMetadata
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	21, // 0: auth.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	21, // 1: auth.v1.Session.last_active_at:type_name -> google.protobuf.Timestamp
	21, // 2: auth.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	22, // 3: auth.v1.LoginWithPasswordRequest.client_context:type_name -> common.v1.ClientContext
	2,  // 4: auth.v1.LoginResponse.tokens:type_name -> auth.v1.TokenPair
	1,  // 5: auth.v1.LoginResponse.session:type_name -> auth.v1.Session
	23, // 6: auth.v1.LoginResponse.metadata:type_name -> common.v1.ResponseMetadata
	22, // 7: auth.v1.SendMagicLinkRequest.client_context:type_name -> common.v1.ClientContext
	23, // 8: auth.v1.SendMagicLinkResponse.metadata:type_name -> common.v1.ResponseMetadata
	22, // 9: auth.v1.VerifyMagicLinkRequest.client_context:type_name -> common.v1.ClientContext
	0,  // 10: auth.v1.InitiateOAuthRequest.provider:type_name -> auth.v1.OAuthProvider
	22, // 11: auth.v1.InitiateOAuthRequest.client_context:type_name -> common.v1.ClientContext
	23, // 12: auth.v1.InitiateOAuthResponse.metadata:type_name -> common.v1.ResponseMetadata
	0,  // 13: auth.v1.CompleteOAuthRequest.provider:type_name -> auth.v1.OAuthProvider
	22, // 14: auth.v1.CompleteOAuthRequest.client_context:type_name -> common.v1.ClientContext
	2,  // 15: auth.v1.RefreshTokenResponse.tokens:type_name -> auth.v1.TokenPair
	23, // 16: auth.v1.RefreshTokenResponse.metadata:type_name -> common.v1.ResponseMetadata
	23, // 17: auth.v1.LogoutResponse.metadata:type_name -> common.v1.ResponseMetadata
	23, // 18: auth.v1.LogoutAllResponse.metadata:type_name -> common.v1.ResponseMetadata
	1,  // 19: auth.v1.GetSessionResponse.session:type_name -> auth.v1.Session
	23, // 20: auth.v1.GetSessionResponse.metadata:type_name -> common.v1.ResponseMetadata
	1,  // 21: auth.v1.ListSessionsResponse.sessions:type_name -> auth.v1.Session
	23, // 22: auth.v1.ListSessionsResponse.metadata:type_name -> common.v1.ResponseMetadata
	3,  // 23: auth.v1.AuthService.LoginWithPassword:input_type -> auth.v1.LoginWithPasswordRequest
	5,  // 24: auth.v1.AuthService.SendMagicLink:input_type -> auth.v1.SendMagicLinkRequest
	7,  // 25: auth.v1.AuthService.VerifyMagicLink:input_type -> auth.v1.VerifyMagicLinkRequest
	8,  // 26: auth.v1.AuthService.InitiateOAuth:input_type -> auth.v1.InitiateOAuthRequest
	10, // 27: auth.v1.AuthService.CompleteOAuth:input_type -> auth.v1.CompleteOAuthRequest
	11, // 28: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	13, // 29: auth.v1.AuthService.Logout:input_type -> auth.v1.LogoutRequest
	15, // 30: auth.v1.AuthService.LogoutAll:input_type -> auth.v1.LogoutAllRequest
	17, // 31: auth.v1.AuthService.GetSession:input_type -> auth.v1.GetSessionRequest
	19, // 32: auth.v1.AuthService.ListSessions:input_type -> auth.v1.ListSessionsRequest
	4,  // 33: auth.v1.AuthService.LoginWithPassword:output_type -> auth.v1.LoginResponse
	6,  // 34: auth.v1.AuthService.SendMagicLink:output_type -> auth.v1.SendMagicLinkResponse
	4,  // 35: auth.v1.AuthService.VerifyMagicLink:output_type -> auth.v1.LoginResponse
	9,  // 36: auth.v1.AuthService.InitiateOAuth:output_type -> auth.v1.InitiateOAuthResponse
	4,  // 37: auth.v1.AuthService.CompleteOAuth:output_type -> auth.v1.LoginResponse
	12, // 38: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenResponse
	14, // 39: auth.v1.AuthService.Logout:output_type -> auth.v1.LogoutResponse
	16, // 40: auth.v1.AuthService.LogoutAll:output_type -> auth.v1.LogoutAllResponse
	18, // 41: auth.v1.AuthService.GetSession:output_type -> auth.v1.GetSessionResponse
	20, // 42: auth.v1.AuthService.ListSessions:output_type -> auth.v1.ListSessionsResponse
	33, // [33:43] is the sub-list for method output_type
	23, // [23:33] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
