package random

import (
	"encoding/base64"
	"encoding/hex"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewGenerator(t *testing.T) {
	gen := NewGenerator()
	assert.NotNil(t, gen)
}

func TestGenerateBytes(t *testing.T) {
	gen := NewGenerator()

	t.Run("generates bytes of correct length", func(t *testing.T) {
		lengths := []int{16, 32, 64, 128}

		for _, length := range lengths {
			result := gen.GenerateBytes(length)

			require.True(t, result.IsOk(), "should generate bytes successfully")
			bytes := result.Unwrap()
			assert.Len(t, bytes, length, "should generate correct number of bytes")
		}
	})

	t.Run("generates unique bytes each time", func(t *testing.T) {
		result1 := gen.GenerateBytes(32)
		result2 := gen.GenerateBytes(32)

		require.True(t, result1.IsOk())
		require.True(t, result2.IsOk())

		bytes1 := result1.Unwrap()
		bytes2 := result2.Unwrap()

		assert.NotEqual(t, bytes1, bytes2, "should generate different bytes each time")
	})

	t.Run("fails with invalid length", func(t *testing.T) {
		invalidLengths := []int{0, -1, -100}

		for _, length := range invalidLengths {
			result := gen.GenerateBytes(length)

			assert.True(t, result.IsErr(), "should fail with invalid length")

			err := result.UnwrapErr()
			_, ok := err.(ErrInvalidLength)
			assert.True(t, ok, "should return ErrInvalidLength")
		}
	})

	t.Run("generates non-zero bytes", func(t *testing.T) {
		result := gen.GenerateBytes(32)

		require.True(t, result.IsOk())
		bytes := result.Unwrap()

		// Check that not all bytes are zero (extremely unlikely with crypto/rand)
		allZero := true
		for _, b := range bytes {
			if b != 0 {
				allZero = false
				break
			}
		}
		assert.False(t, allZero, "generated bytes should not all be zero")
	})
}

func TestGenerateBase64(t *testing.T) {
	gen := NewGenerator()

	t.Run("generates valid base64 token", func(t *testing.T) {
		result := gen.GenerateBase64(32)

		require.True(t, result.IsOk(), "should generate base64 token successfully")
		token := result.Unwrap()

		// Should be non-empty
		assert.NotEmpty(t, token)

		// Should be valid base64 (URL-safe)
		_, err := base64.URLEncoding.DecodeString(token)
		assert.NoError(t, err, "should be valid URL-safe base64")
	})

	t.Run("generates unique tokens each time", func(t *testing.T) {
		result1 := gen.GenerateBase64(32)
		result2 := gen.GenerateBase64(32)

		require.True(t, result1.IsOk())
		require.True(t, result2.IsOk())

		token1 := result1.Unwrap()
		token2 := result2.Unwrap()

		assert.NotEqual(t, token1, token2, "should generate different tokens each time")
	})

	t.Run("generates longer strings for longer byte lengths", func(t *testing.T) {
		result16 := gen.GenerateBase64(16)
		result32 := gen.GenerateBase64(32)
		result64 := gen.GenerateBase64(64)

		require.True(t, result16.IsOk())
		require.True(t, result32.IsOk())
		require.True(t, result64.IsOk())

		token16 := result16.Unwrap()
		token32 := result32.Unwrap()
		token64 := result64.Unwrap()

		assert.Less(t, len(token16), len(token32), "32-byte token should be longer than 16-byte")
		assert.Less(t, len(token32), len(token64), "64-byte token should be longer than 32-byte")
	})

	t.Run("fails with invalid length", func(t *testing.T) {
		result := gen.GenerateBase64(0)

		assert.True(t, result.IsErr(), "should fail with invalid length")
	})

	t.Run("generates URL-safe base64", func(t *testing.T) {
		// Generate many tokens to ensure we get URL-unsafe chars if they exist
		for i := 0; i < 100; i++ {
			result := gen.GenerateBase64(32)
			require.True(t, result.IsOk())

			token := result.Unwrap()

			// URL-safe base64 should not contain '+' or '/'
			assert.NotContains(t, token, "+", "should not contain '+'")
			assert.NotContains(t, token, "/", "should not contain '/'")

			// Should contain '-' or '_' instead (URL-safe chars)
			// Note: Not guaranteed in every token, but checking format is valid
		}
	})
}

func TestGenerateHex(t *testing.T) {
	gen := NewGenerator()

	t.Run("generates valid hex token", func(t *testing.T) {
		result := gen.GenerateHex(32)

		require.True(t, result.IsOk(), "should generate hex token successfully")
		token := result.Unwrap()

		// Should be non-empty
		assert.NotEmpty(t, token)

		// Should be valid hex
		_, err := hex.DecodeString(token)
		assert.NoError(t, err, "should be valid hex")

		// Hex encoding doubles the length (2 hex chars per byte)
		assert.Equal(t, 64, len(token), "hex token should be 2x the byte length")
	})

	t.Run("generates unique tokens each time", func(t *testing.T) {
		result1 := gen.GenerateHex(32)
		result2 := gen.GenerateHex(32)

		require.True(t, result1.IsOk())
		require.True(t, result2.IsOk())

		token1 := result1.Unwrap()
		token2 := result2.Unwrap()

		assert.NotEqual(t, token1, token2, "should generate different tokens each time")
	})

	t.Run("generates correct length hex strings", func(t *testing.T) {
		testCases := []struct {
			byteLength int
			hexLength  int
		}{
			{16, 32},
			{32, 64},
			{64, 128},
		}

		for _, tc := range testCases {
			result := gen.GenerateHex(tc.byteLength)

			require.True(t, result.IsOk())
			token := result.Unwrap()

			assert.Equal(t, tc.hexLength, len(token),
				"hex token should be 2x the byte length")
		}
	})

	t.Run("only contains valid hex characters", func(t *testing.T) {
		result := gen.GenerateHex(32)

		require.True(t, result.IsOk())
		token := result.Unwrap()

		// Should only contain 0-9, a-f
		for _, char := range token {
			assert.True(t,
				(char >= '0' && char <= '9') || (char >= 'a' && char <= 'f'),
				"should only contain hex characters (0-9, a-f)")
		}
	})

	t.Run("fails with invalid length", func(t *testing.T) {
		result := gen.GenerateHex(-1)

		assert.True(t, result.IsErr(), "should fail with invalid length")
	})
}

func TestErrors(t *testing.T) {
	t.Run("ErrInvalidLength", func(t *testing.T) {
		err := ErrInvalidLength{Length: -5}
		assert.Contains(t, err.Error(), "-5")
		assert.Contains(t, err.Error(), "invalid token length")
	})

	t.Run("ErrGenerationFailed", func(t *testing.T) {
		innerErr := assert.AnError
		err := ErrGenerationFailed{Err: innerErr}

		assert.Contains(t, err.Error(), "token generation failed")
		assert.Equal(t, innerErr, err.Unwrap())
	})
}

// Benchmark tests
func BenchmarkGenerateBytes(b *testing.B) {
	gen := NewGenerator()

	b.Run("16 bytes", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			gen.GenerateBytes(16)
		}
	})

	b.Run("32 bytes", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			gen.GenerateBytes(32)
		}
	})

	b.Run("64 bytes", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			gen.GenerateBytes(64)
		}
	})
}

func BenchmarkGenerateBase64(b *testing.B) {
	gen := NewGenerator()

	for i := 0; i < b.N; i++ {
		gen.GenerateBase64(32)
	}
}

func BenchmarkGenerateHex(b *testing.B) {
	gen := NewGenerator()

	for i := 0; i < b.N; i++ {
		gen.GenerateHex(32)
	}
}
